import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get('SUPABASE_URL')||'',SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',ANON=Deno.env.get('SUPABASE_ANON_KEY')||'';
const BOT=Deno.env.get('TELEGRAM_BOT_TOKEN')||'',CHAT=Deno.env.get('TELEGRAM_CHAT_ID')||'',MONITOR=Deno.env.get('MONITOR_SECRET')||'';
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={'Access-Control-Allow-Origin':'https://1specnazov1.github.io','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-monitor-secret','Access-Control-Allow-Methods':'POST, OPTIONS'};
function json(body:unknown,status=200){return Response.json(body,{status,headers:{...cors,'Cache-Control':'no-store'}})}
function safeEq(a:string,b:string){const aa=new TextEncoder().encode(a),bb=new TextEncoder().encode(b);let diff=aa.length^bb.length;for(let i=0;i<Math.max(aa.length,bb.length);i++)diff|=(aa[i]||0)^(bb[i]||0);return diff===0}
async function authorize(req:Request){const supplied=req.headers.get('x-monitor-secret')||'';if(MONITOR.length>=24&&supplied&&safeEq(supplied,MONITOR))return{kind:'system'};const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)throw new Error('Authentication required');const authClient=createClient(URL,ANON,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data,error}=await authClient.auth.getUser(token);if(error||!data?.user?.id)throw new Error('Invalid session');const{data:profile}=await admin.from('crypto_user_profiles').select('role').eq('user_id',data.user.id).maybeSingle();if(profile?.role!=='admin')throw new Error('Admin access required');return{kind:'admin',user_id:data.user.id}}
async function tg(method:string,body?:Record<string,unknown>){if(!BOT)throw new Error('Telegram bot token missing');const response=await fetch(`https://api.telegram.org/bot${BOT}/${method}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok!==true)throw new Error(String(data?.description||`Telegram ${response.status}`));return data.result}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({ok:false,error:'POST only'},405);try{const auth=await authorize(req);const input=await req.json().catch(()=>({}));const action=String(input?.action||'status');if(auth.kind==='system'&&action!=='status')return json({ok:false,error:'System authorization is status-only'},403);const checks:any={bot_token_present:!!BOT,chat_id_present:!!CHAT,monitor_secret:MONITOR.length>=24,bot_api:false,chat_access:false,queue_clear:false};if(!BOT||!CHAT)return json({ok:true,ready:false,checks,error:'Telegram runtime configuration incomplete'});const me=await tg('getMe');checks.bot_api=!!me?.id;const chat=await tg('getChat',{chat_id:CHAT});checks.chat_access=!!chat?.id;const{count}=await admin.from('crypto_signal_notification_outbox').select('id',{count:'exact',head:true}).in('status',['pending','failed']).lte('available_at',new Date().toISOString());checks.queue_clear=Number(count||0)===0;if(action==='test')await tg('sendMessage',{chat_id:CHAT,text:`✅ CRYPTO LAB · Telegram pre-flight OK\n${new Date().toISOString()}\nЭто тестовое сообщение. Торговый сигнал не создан.`,disable_web_page_preview:true});return json({ok:true,ready:Object.values(checks).every(Boolean),action,checks,bot:{id:me?.id,username:me?.username},chat:{id:chat?.id,type:chat?.type,title:chat?.title||chat?.username||null},pending_notifications:Number(count||0)});}catch(error){const msg=error instanceof Error?error.message:String(error);return json({ok:false,ready:false,error:msg},/auth|required|session/i.test(msg)?401:500)}});
