import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const ORIGIN="https://1specnazov1.github.io";
const CALLBACK="https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-x-oauth-callback";
const VERIFY_FRESH_MS=24*60*60*1000;
const STALE_GRACE_MS=7*24*60*60*1000;
const OAUTH_TTL_MS=10*60*1000;
function env(n:string){const v=Deno.env.get(n)?.trim();if(!v)throw new Error(`Missing ${n}`);return v}
function cors(o:string|null){return {"Access-Control-Allow-Origin":o===ORIGIN?o:ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS",Vary:"Origin"}}
function json(b:unknown,s=200,o:string|null=null){return Response.json(b,{status:s,headers:{...cors(o),"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
function pct(v:string){return encodeURIComponent(v).replace(/[!'()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`)}
function nonce(){const b=crypto.getRandomValues(new Uint8Array(18));return [...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function b64(b:Uint8Array){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s)}
function unb64(s:string){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function aesKey(){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(env("SUPABASE_SERVICE_ROLE_KEY")+":crypto-lab-x-follower:v1"));return crypto.subtle.importKey("raw",d,{name:"AES-GCM"},false,["encrypt","decrypt"])}
async function enc(v:string){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await aesKey(),out=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(v));return {cipher:b64(new Uint8Array(out)),iv:b64(iv)}}
async function dec(cipher:string,iv:string){const key=await aesKey(),out=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv)},key,unb64(cipher));return new TextDecoder().decode(out)}
async function oauthHeader(method:string,rawUrl:string,token:string,tokenSecret:string,extra:Record<string,string>={}){const oauth:Record<string,string>={oauth_consumer_key:env("X_API_KEY"),oauth_nonce:nonce(),oauth_signature_method:"HMAC-SHA1",oauth_timestamp:String(Math.floor(Date.now()/1000)),oauth_version:"1.0",...extra};if(token)oauth.oauth_token=token;const u=new URL(rawUrl),pairs:[string,string][]=[...u.searchParams.entries(),...Object.entries(oauth)];pairs.sort((a,b)=>pct(a[0])===pct(b[0])?pct(a[1]).localeCompare(pct(b[1])):pct(a[0]).localeCompare(pct(b[0])));const normalized=pairs.map(([k,v])=>`${pct(k)}=${pct(v)}`).join("&"),base=`${method.toUpperCase()}&${pct(`${u.protocol}//${u.host}${u.pathname}`)}&${pct(normalized)}`,signing=`${pct(env("X_API_SECRET"))}&${pct(tokenSecret)}`,key=await crypto.subtle.importKey("raw",new TextEncoder().encode(signing),{name:"HMAC",hash:"SHA-1"},false,["sign"]),sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(base));oauth.oauth_signature=btoa(String.fromCharCode(...new Uint8Array(sig)));return `OAuth ${Object.entries(oauth).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${pct(k)}="${pct(v)}"`).join(", ")}`}
async function followsTarget(targetId:string,token:string,secret:string){const u=new URL(`https://api.x.com/2/users/${encodeURIComponent(targetId)}`);u.searchParams.set("user.fields","connection_status,username");const url=u.toString(),r=await fetch(url,{headers:{Authorization:await oauthHeader("GET",url,token,secret),Accept:"application/json"}}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`X relationship ${r.status}: ${b?.detail||b?.title||"request failed"}`);const status=Array.isArray(b?.data?.connection_status)?b.data.connection_status.map((x:any)=>String(x).toLowerCase()):[];return status.includes("following")}

Deno.serve(async req=>{const origin=req.headers.get("Origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(req.method!=="POST")return json({ok:false,error:"POST required"},405,origin);try{const supa=env("SUPABASE_URL"),service=env("SUPABASE_SERVICE_ROLE_KEY"),admin=createClient(supa,service,{auth:{persistSession:false,autoRefreshToken:false}}),auth=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!auth)return json({ok:false,error:"Authentication required"},401,origin);const {data:{user},error:uerr}=await admin.auth.getUser(auth);if(uerr||!user)return json({ok:false,error:"Authentication required"},401,origin);const body=await req.json().catch(()=>({})),action=String(body?.action||"status").slice(0,24);const {data:profile}=await admin.from("crypto_user_profiles").select("role").eq("user_id",user.id).maybeSingle();if(profile?.role==="admin"&&action!=="start")return json({ok:true,allowed:true,bypass:"admin",target_handle:"@CryptoLabPulse"},200,origin);const {data:settings}=await admin.from("crypto_x_settings").select("account_user_id,account_handle").eq("singleton",true).maybeSingle();const targetId=String(settings?.account_user_id||""),targetHandle=String(settings?.account_handle||"@CryptoLabPulse");if(!targetId)return json({ok:false,error:"X target account is not configured"},503,origin);
if(action==="start"){await admin.from("crypto_x_oauth_requests").delete().lt("expires_at",new Date().toISOString());const requestUrl="https://api.x.com/oauth/request_token?x_auth_access_type=read",r=await fetch(requestUrl,{method:"POST",headers:{Authorization:await oauthHeader("POST",requestUrl,"","",{oauth_callback:CALLBACK}),"Content-Type":"application/x-www-form-urlencoded"},body:""}),text=await r.text();if(!r.ok)throw new Error(`X OAuth request_token ${r.status}: ${text.slice(0,300)}`);const p=new URLSearchParams(text),requestToken=p.get("oauth_token")||"",requestSecret=p.get("oauth_token_secret")||"",confirmed=p.get("oauth_callback_confirmed");if(!requestToken||!requestSecret||confirmed!=="true")throw new Error("X OAuth request token unavailable");const e=await enc(requestSecret);await admin.from("crypto_x_oauth_requests").delete().eq("user_id",user.id);const {error:ie}=await admin.from("crypto_x_oauth_requests").insert({request_token_hash:await sha(requestToken),request_secret_ciphertext:e.cipher,request_secret_iv:e.iv,user_id:user.id,expires_at:new Date(Date.now()+OAUTH_TTL_MS).toISOString()});if(ie)throw ie;return json({ok:true,allowed:false,authorize_url:`https://api.x.com/oauth/authenticate?oauth_token=${encodeURIComponent(requestToken)}`,target_handle:targetHandle,access_type:"read"},200,origin)}
let {data:access}=await admin.from("crypto_x_follower_access").select("*").eq("user_id",user.id).maybeSingle();if(!access)return json({ok:true,allowed:false,code:"X_NOT_CONNECTED",target_handle:targetHandle,connect_required:true},200,origin);if(access.revoked_at)return json({ok:true,allowed:false,code:"X_ACCESS_REVOKED",target_handle:targetHandle,connect_required:true},200,origin);const last=access.last_checked_at?new Date(access.last_checked_at).getTime():0,force=body?.force===true,needs=force||!last||Date.now()-last>VERIFY_FRESH_MS||access.follows_target!==true;if(needs){try{if(!access.oauth_token_ciphertext||!access.oauth_secret_ciphertext)throw new Error("X authorization needs renewal");const token=await dec(access.oauth_token_ciphertext,access.oauth_token_iv),secret=await dec(access.oauth_secret_ciphertext,access.oauth_secret_iv),follows=await followsTarget(targetId,token,secret),now=new Date().toISOString();const patch:any={follows_target:follows,last_checked_at:now,updated_at:now,check_error:null};if(follows)patch.verified_at=now;const {data:a2,error:ue}=await admin.from("crypto_x_follower_access").update(patch).eq("user_id",user.id).select("*").single();if(ue)throw ue;access=a2}catch(err){const verified=access.verified_at?new Date(access.verified_at).getTime():0;if(access.follows_target===true&&verified&&Date.now()-verified<=STALE_GRACE_MS)return json({ok:true,allowed:true,stale:true,code:"X_RECHECK_TEMPORARILY_UNAVAILABLE",x_username:access.x_username,target_handle:targetHandle},200,origin);await admin.from("crypto_x_follower_access").update({check_error:String(err).slice(0,500),updated_at:new Date().toISOString()}).eq("user_id",user.id);return json({ok:false,allowed:false,code:"X_RECHECK_FAILED",error:"Could not verify X follow status right now",target_handle:targetHandle},503,origin)}}
return json({ok:true,allowed:access.follows_target===true,code:access.follows_target===true?"FOLLOWER_VERIFIED":"FOLLOW_REQUIRED",x_username:access.x_username,target_handle:targetHandle,verified_at:access.verified_at,last_checked_at:access.last_checked_at,connect_required:false},200,origin)}catch(e){console.error("crypto-x-auth-check",e);return json({ok:false,allowed:false,error:e instanceof Error?e.message:"X access check failed"},500,origin)}});
