import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const admin=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:CORS})}
const sym=(v:unknown)=>String(v||'BTC').toUpperCase().replace(/USDT$/,'').replace(/[^A-Z0-9]/g,'').slice(0,20)||'BTC';
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:null};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST only'},405);try{const auth=req.headers.get('authorization')||'';const token=auth.replace(/^Bearer\s+/i,'').trim();if(!token)return json({error:'AUTH_REQUIRED'},401);const {data:userData,error:userError}=await admin.auth.getUser(token);if(userError||!userData.user)return json({error:'AUTH_REQUIRED'},401);const {data:rate,error:rateError}=await admin.rpc('reserve_crypto_feature_rate',{p_user_id:userData.user.id,p_feature:'smart_money',p_limit:30,p_window_seconds:60});if(rateError)throw rateError;if(rate?.allowed===false){if(rate?.code==='X_FOLLOWER_REQUIRED'||rate?.entitled===false)return json({supported:false,error:'Verified @CryptoLabPulse follower access required',code:'X_FOLLOWER_REQUIRED'},403);return json({supported:false,error:'SMART MONEY rate limit reached',code:'RATE_LIMITED',retry_after_seconds:rate.retry_after_seconds},429)}const body=await req.json().catch(()=>({}));const symbol=sym(body?.symbol),timeframe=String(body?.timeframe||'5M').toUpperCase();const r=await fetch(`${SUPABASE_URL}/functions/v1/crypto-smart-money`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({symbol,timeframe}),cache:'no-store'});const current=await r.json().catch(()=>({}));if(!r.ok||current?.ok===false)return json({supported:false,error:current?.error||`SMART MONEY ${r.status}`},r.status||503);const since=new Date(Date.now()-24*60*60*1000).toISOString();const {data:hist}=await admin.from('crypto_smart_money_snapshots').select('captured_at,smart_score,smart_direction,whale_pressure,cvd_pressure,open_interest_change_pct,funding_rate,orderbook_imbalance').eq('symbol',symbol).gte('captured_at',since).order('captured_at',{ascending:true}).limit(400);const normalized={...current,supported:true,rate:{remaining:rate?.remaining??null,window_seconds:60},whale_pressure:n(current.whale_pressure)===null?null:Number(current.whale_pressure)/100,cvd_pressure:n(current.cvd_pressure)===null?null:Number(current.cvd_pressure)/100,orderbook_imbalance:n(current.orderbook_imbalance)===null?null:Number(current.orderbook_imbalance)/100,flow_history:(hist||[]).map((x:any)=>({timestamp:new Date(x.captured_at).getTime(),pressure:(n(x.smart_score)??0)/100,score:n(x.smart_score),direction:x.smart_direction,whale_pressure:n(x.whale_pressure)===null?null:Number(x.whale_pressure)/100,cvd_pressure:n(x.cvd_pressure)===null?null:Number(x.cvd_pressure)/100,oi_change_pct:n(x.open_interest_change_pct),funding_rate:n(x.funding_rate),orderbook_imbalance:n(x.orderbook_imbalance)===null?null:Number(x.orderbook_imbalance)/100}))};return json(normalized);}catch(e){console.error('crypto-lab-v79-smart-money',e);return json({supported:false,error:e instanceof Error?e.message:String(e)},500)}});