import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get('SUPABASE_URL')||'';
const ANON=Deno.env.get('SUPABASE_ANON_KEY')||'';
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const ALLOWED=new Set(['https://1specnazov1.github.io','http://localhost:5500','http://127.0.0.1:5500','http://localhost:4173','http://127.0.0.1:4173']);
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
function headers(origin:string|null){const o=origin&&ALLOWED.has(origin)?origin:'https://1specnazov1.github.io';return {'Access-Control-Allow-Origin':o,'Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'};}
function json(body:unknown,status:number,origin:string|null){return new Response(JSON.stringify(body),{status,headers:headers(origin)});}
async function userRpc(auth:string,name:string,args:Record<string,unknown>){const r=await fetch(`${URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{Authorization:auth,apikey:ANON,'Content-Type':'application/json'},body:JSON.stringify(args)});const d=await r.json().catch(()=>({}));if(!r.ok){const e:any=new Error(d?.message||d?.error||`${name} failed`);e.status=r.status;throw e;}return d;}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(origin)});if(req.method!=='POST')return json({ok:false,error:'POST required',code:'METHOD_NOT_ALLOWED'},405,origin);const auth=req.headers.get('authorization')||'';if(!/^Bearer\s+\S+/i.test(auth))return json({ok:false,error:'Authentication required',code:'AUTH_REQUIRED'},401,origin);try{const token=auth.replace(/^Bearer\s+/i,'');const {data,error}=await admin.auth.getUser(token);const user=data?.user;if(error||!user?.id)return json({ok:false,error:'Authentication required',code:'AUTH_REQUIRED'},401,origin);const {data:rate,error:rateError}=await admin.rpc('reserve_crypto_feature_rate',{p_user_id:user.id,p_feature:'chart',p_limit:30,p_window_seconds:60});if(rateError)throw rateError;if(rate?.allowed===false)return json({ok:false,error:'Too many Chart requests. Try again shortly.',code:'RATE_LIMITED',retry_after_seconds:rate.retry_after_seconds},429,origin);const status=await userRpc(auth,'get_crypto_feature_status',{p_feature:'chart'});if(status?.allowed===false)return json({ok:false,error:'Daily Chart & Analytics limit reached',code:'QUOTA_EXCEEDED',quota:status},429,origin);const quota=await userRpc(auth,'consume_crypto_feature',{p_feature:'chart'});if(!quota?.allowed)return json({ok:false,error:'Daily Chart & Analytics limit reached',code:'QUOTA_EXCEEDED',quota},429,origin);return json({ok:true,feature:'chart',quota,rate:{remaining:rate?.remaining??null,window_seconds:60}},200,origin);}catch(error){console.error('crypto-lab-v79-chart',error);const status=Number((error as any)?.status)||500;return json({ok:false,error:status===401?'Authentication required':'Chart access check failed',code:status===401?'AUTH_REQUIRED':'CHART_GATE_ERROR'},status,origin);}});
