'use strict';
(() => {
  const ENDPOINT='https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-lab-v79-access';
  const TURNSTILE='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';
  const AUTH_KEY='sb-txhzxbizjpinowepfjkm-auth-token';
  const DEVICE_KEY='cryptoLabEmailAccessDeviceV1';
  const EMAIL_KEY='cryptoLabEmailAccessEmailV1';
  if(location.hostname==='127.0.0.1'||location.hostname==='localhost')return;

  const TEXT={
    ru:{title:'CRYPTO LAB FREE',sub:'Создайте FREE аккаунт. Если аккаунт уже есть, можно войти паролем или получить одноразовую ссылку на email.',signup:'Создать FREE аккаунт',label:'Email для одноразового входа',placeholder:'name@example.com',send:'Отправить одноразовую ссылку',login:'Войти с паролем',device:'Для одноразовой ссылки откройте письмо на этом же устройстве и в этом же браузере. Пересланная ссылка на другом устройстве не сработает.',privacy:'Email используется только для авторизации и работы аккаунта.',captcha:'Подтвердите, что вы не робот.',legal:'Для доступа по email необходимо принять актуальные документы:',terms:'Условия использования',risk:'Предупреждение о рисках',privacyDoc:'Политика конфиденциальности',legalBad:'Примите все актуальные документы.',bad:'Не удалось отправить ссылку. Попробуйте позже.',ok:'Ссылка отправлена на {email}. Откройте письмо на этом же устройстве и в этом же браузере.',working:'Отправка…'},
    uk:{title:'CRYPTO LAB FREE',sub:'Створіть FREE акаунт. Якщо акаунт уже є, можна увійти паролем або отримати одноразове посилання на email.',signup:'Створити FREE акаунт',label:'Email для одноразового входу',placeholder:'name@example.com',send:'Надіслати одноразове посилання',login:'Увійти з паролем',device:'Для одноразового посилання відкрийте лист на цьому самому пристрої та в цьому самому браузері. Переслане посилання на іншому пристрої не спрацює.',privacy:'Email використовується лише для авторизації та роботи акаунта.',captcha:'Підтвердьте, що ви не робот.',legal:'Для доступу через email необхідно прийняти актуальні документи:',terms:'Умови використання',risk:'Попередження про ризики',privacyDoc:'Політика конфіденційності',legalBad:'Прийміть усі актуальні документи.',bad:'Не вдалося надіслати посилання. Спробуйте пізніше.',ok:'Посилання надіслано на {email}. Відкрийте лист на цьому самому пристрої та в цьому самому браузері.',working:'Надсилання…'},
    en:{title:'CRYPTO LAB FREE',sub:'Create a FREE account. If you already have one, sign in with your password or use a one-time email access link.',signup:'Create FREE account',label:'Email for one-time access',placeholder:'name@example.com',send:'Send one-time access link',login:'Sign in with password',device:'For one-time access, open the email on the same device and in the same browser. A forwarded link opened elsewhere will not grant access.',privacy:'Your email is used only for authentication and account operation.',captcha:'Complete the anti-bot check.',legal:'For one-time email access, accept the current documents:',terms:'Terms of Use',risk:'Risk Warning',privacyDoc:'Privacy Notice',legalBad:'Accept all current documents.',bad:'Could not send the access link. Try again later.',ok:'Access link sent to {email}. Open it on the same device and in the same browser.',working:'Sending…'}
  };

  function hasSession(){try{const raw=localStorage.getItem(AUTH_KEY);if(!raw)return false;const data=JSON.parse(raw);const session=Array.isArray(data)?data[0]:data?.currentSession||data?.session||data;return !!session?.access_token&&(!session?.expires_at||Number(session.expires_at)*1000>Date.now()-60000)}catch{return false}}
  if(hasSession())return;
  const locale=()=>typeof lang==='string'&&TEXT[lang]?lang:'en';
  const t=()=>TEXT[locale()];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const docLabel=key=>key==='terms'?t().terms:key==='risk'?t().risk:t().privacyDoc;
  function randomSecret(){const b=new Uint8Array(32);crypto.getRandomValues(b);let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
  async function sha256Hex(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}

  const style=document.createElement('style');style.id='cryptoAccessGateStyles';style.textContent=`
  .access-gate{position:fixed;z-index:1000;inset:0;display:grid;place-items:center;padding:20px;background:rgba(6,8,11,.96);backdrop-filter:blur(10px);overflow:auto}
  .access-gate-card{width:min(540px,100%);border:1px solid #343b45;border-radius:16px;background:#12171d;box-shadow:0 28px 80px #000b;padding:24px;color:#eaecef}
  .access-gate-brand{display:flex;align-items:center;gap:10px;margin-bottom:18px}.access-gate-logo{width:42px;height:42px;border-radius:11px;background:#f0b90b;color:#111;display:grid;place-items:center;font-weight:1000;font-size:18px}.access-gate-brand b{letter-spacing:.08em}.access-gate-brand small{display:block;color:#848e9c;margin-top:2px}
  .access-gate-card h2{font-size:24px;margin:0 0 8px}.access-gate-card p{color:#9ba5b3;line-height:1.55;margin:0 0 14px}.access-gate-field label{display:block;color:#9ba5b3;font-size:11px;margin-bottom:6px}.access-gate-field input{width:100%;background:#1e2329;border:1px solid #343b45;color:#fff;border-radius:9px;padding:12px;font-size:16px;outline:none}.access-gate-field input:focus{border-color:#f0b90b88}
  .access-gate-device{padding:10px 11px;border:1px solid #f0b90b44;background:#f0b90b0d;border-radius:9px;color:#dfc77c;font-size:10px;line-height:1.5;margin:12px 0}.access-gate-legal{padding:10px 11px;background:#0d1117;border:1px solid #2b3139;border-radius:9px;margin:12px 0}.access-gate-legal-title{font-size:10px;color:#9ba5b3;margin-bottom:8px}.access-gate-check{display:flex;align-items:flex-start;gap:8px;margin:7px 0;color:#cbd3de;font-size:10px}.access-gate-check input{margin-top:2px}.access-gate-check a{color:#b9d9ff;text-decoration:none}.access-gate-check a:hover{text-decoration:underline}
  .access-gate-turnstile{min-height:1px;margin:13px 0}.access-gate-actions{display:grid;gap:8px}.access-gate-actions button{min-height:44px;border-radius:9px;padding:10px 12px;font-weight:800;cursor:pointer}.access-gate-submit{border:1px solid #f0b90b;background:#f0b90b;color:#111}.access-gate-login{border:1px solid #343b45;background:#1e2329;color:#eaecef}.access-gate-note{font-size:10px!important;color:#75808e!important;margin-top:12px!important}.access-gate-msg{display:none;margin:12px 0;padding:10px;border-radius:8px;font-size:11px;line-height:1.5}.access-gate-msg.show{display:block}.access-gate-msg.ok{color:#a7f3d0;border:1px solid #0ecb8144;background:#0ecb8110}.access-gate-msg.bad{color:#ffc4cd;border:1px solid #f6465d44;background:#f6465d10}
  @media(max-width:480px){.access-gate{padding:12px;place-items:start center}.access-gate-card{padding:18px;border-radius:13px;margin-top:10px}.access-gate-card h2{font-size:21px}}
  `;document.head.appendChild(style);

  const gate=document.createElement('div');gate.id='cryptoAccessGate';gate.className='access-gate';gate.innerHTML=`<div class="access-gate-card"><div class="access-gate-brand"><div class="access-gate-logo">₿</div><div><b>CRYPTO LAB</b><small>v79 · FREE FOLLOWER ACCESS</small></div></div><h2 id="accessGateTitle"></h2><p id="accessGateSub"></p><form id="accessGateForm"><div class="access-gate-actions"><button class="access-gate-submit" id="accessGateSignup" type="button"></button></div><div class="access-gate-field" style="margin-top:14px"><label id="accessGateLabel" for="accessGateEmail"></label><input id="accessGateEmail" type="email" autocomplete="email" maxlength="254" required></div><input id="accessGateWebsite" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px"><div id="accessGateDevice" class="access-gate-device"></div><div id="accessGateLegal" class="access-gate-legal"></div><div id="accessGateTurnstile" class="access-gate-turnstile"></div><div id="accessGateMsg" class="access-gate-msg"></div><div class="access-gate-actions"><button class="access-gate-login" id="accessGateSubmit" type="submit"></button><button class="access-gate-login" id="accessGateLogin" type="button"></button></div><p class="access-gate-note" id="accessGatePrivacy"></p></form></div>`;document.body.appendChild(gate);

  const $=id=>document.getElementById(id);let cfg=null,token='',widget=null,loading=false;
  function labels(){const c=t();$('accessGateTitle').textContent=c.title;$('accessGateSub').textContent=c.sub;$('accessGateSignup').textContent=c.signup;$('accessGateLabel').textContent=c.label;$('accessGateEmail').placeholder=c.placeholder;$('accessGateSubmit').textContent=loading?c.working:c.send;$('accessGateLogin').textContent=c.login;$('accessGateDevice').textContent=c.device;$('accessGatePrivacy').textContent=c.privacy;renderLegal()}
  function msg(text,type){const box=$('accessGateMsg');box.textContent=text;box.className=`access-gate-msg show ${type}`}
  function renderLegal(){const box=$('accessGateLegal');if(!cfg?.documents?.length){box.innerHTML=`<div class="access-gate-legal-title">${esc(t().legal)}</div>`;return}box.innerHTML=`<div class="access-gate-legal-title">${esc(t().legal)}</div>`+cfg.documents.map(d=>`<label class="access-gate-check"><input type="checkbox" data-legal-key="${esc(d.key)}" data-legal-version="${esc(d.version)}"><span><a href="${esc(d.url||'#')}?lang=${encodeURIComponent(locale())}" target="_blank" rel="noopener">${esc(docLabel(d.key))}</a> · ${esc(d.version)}</span></label>`).join('')}
  function legalAcceptances(){return [...document.querySelectorAll('[data-legal-key]')].filter(x=>x.checked).map(x=>({key:x.dataset.legalKey,version:x.dataset.legalVersion}))}
  function allLegalAccepted(){const a=[...document.querySelectorAll('[data-legal-key]')];return a.length>0&&a.every(x=>x.checked)}
  function loadTurnstile(){return new Promise((resolve,reject)=>{if(window.turnstile)return resolve(window.turnstile);const s=document.createElement('script');s.src=TURNSTILE;s.async=true;s.defer=true;s.onload=()=>resolve(window.turnstile);s.onerror=reject;document.head.appendChild(s)})}
  async function init(){labels();try{const r=await fetch(ENDPOINT,{cache:'no-store'}),b=await r.json();if(!r.ok||!b?.request_enabled||b?.mode!=='email_bound')throw Error();cfg=b;labels();const api=await loadTurnstile();widget=api.render('accessGateTurnstile',{sitekey:cfg.site_key,action:cfg.captcha_action||'crypto_access_request',theme:'dark',size:'flexible',callback:v=>token=v,'expired-callback':()=>token='','error-callback':()=>token=''})}catch{msg(t().bad,'bad');$('accessGateSubmit').disabled=true}}

  $('accessGateForm').onsubmit=async e=>{e.preventDefault();if(loading)return;const email=$('accessGateEmail').value.trim().toLowerCase();if(!allLegalAccepted())return msg(t().legalBad,'bad');if(!token)return msg(t().captcha,'bad');loading=true;labels();$('accessGateSubmit').disabled=true;try{const secret=randomSecret();localStorage.setItem(DEVICE_KEY,secret);localStorage.setItem(EMAIL_KEY,email);const deviceHash=await sha256Hex(secret);const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'request',email,locale:locale(),device_hash:deviceHash,captcha_token:token,legal_acceptances:legalAcceptances(),website:$('accessGateWebsite').value})}),b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error||t().bad);msg(t().ok.replace('{email}',b.masked_email||email),'ok');$('accessGateEmail').disabled=true;$('accessGateSubmit').hidden=true;document.querySelectorAll('[data-legal-key]').forEach(x=>x.disabled=true);if(widget!==null&&window.turnstile)window.turnstile.reset(widget)}catch(err){msg(err instanceof Error?err.message:t().bad,'bad');token='';localStorage.removeItem(DEVICE_KEY);if(widget!==null&&window.turnstile)window.turnstile.reset(widget);$('accessGateSubmit').disabled=false}finally{loading=false;labels()}};
  $('accessGateSignup').onclick=()=>{location.href='./account.html?signup=1'};
  $('accessGateLogin').onclick=()=>{location.href='./account.html?login=1'};
  document.getElementById('lang')?.addEventListener('change',()=>setTimeout(labels,0));
  init();
})();