'use strict';
(() => {
  const ENDPOINT='https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-lab-v79-access';
  const TURNSTILE='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';
  const AUTH_KEY='sb-txhzxbizjpinowepfjkm-auth-token';
  const q=new URLSearchParams(location.search);
  if(location.hostname==='127.0.0.1'||location.hostname==='localhost')return;
  const TEXT={
    ru:{title:'Доступ к CRYPTO LAB',sub:'CRYPTO LAB сейчас бесплатный. Доступ выдаётся по персональному приглашению.',label:'Введите ваш email',placeholder:'name@example.com',send:'Отправить заявку',login:'У меня уже есть доступ — Войти',note:'После одобрения владелец CRYPTO LAB передаст вам персональную одноразовую ссылку.',captcha:'Подтвердите, что вы не робот.',bad:'Не удалось отправить заявку. Попробуйте позже.',ok:'Заявка отправлена. После одобрения вы получите персональную ссылку от владельца.',working:'Отправка…'},
    uk:{title:'Доступ до CRYPTO LAB',sub:'CRYPTO LAB зараз безкоштовний. Доступ надається за персональним запрошенням.',label:'Введіть ваш email',placeholder:'name@example.com',send:'Надіслати заявку',login:'У мене вже є доступ — Увійти',note:'Після схвалення власник CRYPTO LAB передасть вам персональне одноразове посилання.',captcha:'Підтвердьте, що ви не робот.',bad:'Не вдалося надіслати заявку. Спробуйте пізніше.',ok:'Заявку надіслано. Після схвалення ви отримаєте персональне посилання від власника.',working:'Надсилання…'},
    en:{title:'Access CRYPTO LAB',sub:'CRYPTO LAB is currently free. Access is granted by a personal invitation.',label:'Enter your email',placeholder:'name@example.com',send:'Request access',login:'I already have access — Sign in',note:'After approval, the CRYPTO LAB owner will send you a personal one-time invitation link.',captcha:'Complete the anti-bot check.',bad:'Could not submit the request. Try again later.',ok:'Request sent. After approval, the owner will send you a personal invitation link.',working:'Sending…'}
  };
  function hasSession(){try{const raw=localStorage.getItem(AUTH_KEY);if(!raw)return false;const data=JSON.parse(raw);const session=Array.isArray(data)?data[0]:data?.currentSession||data?.session||data;return !!session?.access_token&&(!session?.expires_at||Number(session.expires_at)*1000>Date.now()-60000)}catch{return false}}
  if(hasSession()||q.get('login')==='1'||q.get('auth'))return;
  const locale=()=>typeof lang==='string'&&TEXT[lang]?lang:'ru';
  const t=()=>TEXT[locale()];
  const style=document.createElement('style');style.id='cryptoAccessGateStyles';style.textContent=`
  .access-gate{position:fixed;z-index:1000;inset:0;display:grid;place-items:center;padding:20px;background:rgba(6,8,11,.94);backdrop-filter:blur(10px)}
  .access-gate-card{width:min(520px,100%);border:1px solid #343b45;border-radius:16px;background:#12171d;box-shadow:0 28px 80px #000b;padding:24px;color:#eaecef}
  .access-gate-brand{display:flex;align-items:center;gap:10px;margin-bottom:18px}.access-gate-logo{width:42px;height:42px;border-radius:11px;background:#f0b90b;color:#111;display:grid;place-items:center;font-weight:1000;font-size:18px}.access-gate-brand b{letter-spacing:.08em}.access-gate-brand small{display:block;color:#848e9c;margin-top:2px}
  .access-gate-card h2{font-size:24px;margin:0 0 8px}.access-gate-card p{color:#9ba5b3;line-height:1.55;margin:0 0 16px}.access-gate-field label{display:block;color:#9ba5b3;font-size:11px;margin-bottom:6px}.access-gate-field input{width:100%;background:#1e2329;border:1px solid #343b45;color:#fff;border-radius:9px;padding:12px;font-size:16px;outline:none}.access-gate-field input:focus{border-color:#f0b90b88}
  .access-gate-turnstile{min-height:1px;margin:13px 0}.access-gate-actions{display:grid;gap:8px}.access-gate-actions button{min-height:44px;border-radius:9px;padding:10px 12px;font-weight:800;cursor:pointer}.access-gate-submit{border:1px solid #f0b90b;background:#f0b90b;color:#111}.access-gate-login{border:1px solid #343b45;background:#1e2329;color:#eaecef}.access-gate-note{font-size:10px!important;color:#75808e!important;margin-top:12px!important}.access-gate-msg{display:none;margin:12px 0;padding:10px;border-radius:8px;font-size:11px}.access-gate-msg.show{display:block}.access-gate-msg.ok{color:#a7f3d0;border:1px solid #0ecb8144;background:#0ecb8110}.access-gate-msg.bad{color:#ffc4cd;border:1px solid #f6465d44;background:#f6465d10}
  @media(max-width:480px){.access-gate{padding:12px}.access-gate-card{padding:18px;border-radius:13px}.access-gate-card h2{font-size:21px}}
  `;document.head.appendChild(style);
  const gate=document.createElement('div');gate.id='cryptoAccessGate';gate.className='access-gate';gate.innerHTML=`<div class="access-gate-card"><div class="access-gate-brand"><div class="access-gate-logo">₿</div><div><b>CRYPTO LAB</b><small>v79 · FREE INVITE ACCESS</small></div></div><h2 id="accessGateTitle"></h2><p id="accessGateSub"></p><form id="accessGateForm"><div class="access-gate-field"><label id="accessGateLabel" for="accessGateEmail"></label><input id="accessGateEmail" type="email" autocomplete="email" maxlength="254" required></div><input id="accessGateWebsite" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px"><div id="accessGateTurnstile" class="access-gate-turnstile"></div><div id="accessGateMsg" class="access-gate-msg"></div><div class="access-gate-actions"><button class="access-gate-submit" id="accessGateSubmit" type="submit"></button><button class="access-gate-login" id="accessGateLogin" type="button"></button></div><p class="access-gate-note" id="accessGateNote"></p></form></div>`;document.body.appendChild(gate);
  const $=id=>document.getElementById(id);let cfg=null,token='',widget=null,loading=false;
  function labels(){const c=t();$('accessGateTitle').textContent=c.title;$('accessGateSub').textContent=c.sub;$('accessGateLabel').textContent=c.label;$('accessGateEmail').placeholder=c.placeholder;$('accessGateSubmit').textContent=loading?c.working:c.send;$('accessGateLogin').textContent=c.login;$('accessGateNote').textContent=c.note}
  function msg(text,type){const box=$('accessGateMsg');box.textContent=text;box.className=`access-gate-msg show ${type}`}
  function loadTurnstile(){return new Promise((resolve,reject)=>{if(window.turnstile)return resolve(window.turnstile);const s=document.createElement('script');s.src=TURNSTILE;s.async=true;s.defer=true;s.onload=()=>resolve(window.turnstile);s.onerror=reject;document.head.appendChild(s)})}
  async function init(){labels();try{const r=await fetch(ENDPOINT,{cache:'no-store'}),b=await r.json();if(!r.ok||!b?.request_enabled)throw Error();cfg=b;const api=await loadTurnstile();widget=api.render('accessGateTurnstile',{sitekey:cfg.site_key,action:cfg.captcha_action||'crypto_access_request',theme:'dark',size:'flexible',callback:v=>token=v,'expired-callback':()=>token='','error-callback':()=>token=''})}catch{msg(t().bad,'bad');$('accessGateSubmit').disabled=true}}
  $('accessGateForm').onsubmit=async e=>{e.preventDefault();if(loading)return;const email=$('accessGateEmail').value.trim();if(!token)return msg(t().captcha,'bad');loading=true;labels();$('accessGateSubmit').disabled=true;try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'request',email,locale:locale(),captcha_token:token,website:$('accessGateWebsite').value})}),b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error||t().bad);msg(t().ok,'ok');$('accessGateEmail').disabled=true;$('accessGateSubmit').hidden=true;if(widget!==null&&window.turnstile)window.turnstile.reset(widget)}catch(err){msg(err instanceof Error?err.message:t().bad,'bad');token='';if(widget!==null&&window.turnstile)window.turnstile.reset(widget);$('accessGateSubmit').disabled=false}finally{loading=false;labels()}};
  $('accessGateLogin').onclick=()=>{location.href='./app.html?route=account&login=1'};
  document.getElementById('lang')?.addEventListener('change',()=>setTimeout(labels,0));
  init();
})();