'use strict';
(() => {
  const ENDPOINT='crypto-lab-v79-access-admin';
  let busy=false,state=[];
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const when=v=>{try{return new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return'—'}};
  function mount(){const dashboard=document.getElementById('dashboard');if(!dashboard||document.getElementById('accessAdminPanel'))return;const style=document.createElement('style');style.id='accessAdminStyles';style.textContent='.access-admin-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.access-admin-stat{padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--p2)}.access-admin-stat span{display:block;color:var(--m);font-size:9px;text-transform:uppercase}.access-admin-stat b{display:block;font-size:18px;margin-top:5px}.access-request{border:1px solid var(--line);border-radius:9px;margin:9px 0;padding:10px}.access-request-head{display:flex;justify-content:space-between;gap:10px}.access-request-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.access-link{margin-top:9px;padding:9px;border:1px solid #f0b90b55;border-radius:8px;background:#f0b90b0d}.access-link input{width:100%;margin-top:6px}.access-request code{color:#b9d9ff}@media(max-width:760px){.access-admin-stats{grid-template-columns:1fr 1fr}.access-request-head{flex-direction:column}}@media(max-width:480px){.access-admin-stats{grid-template-columns:1fr}}';document.head.appendChild(style);const section=document.createElement('section');section.id='accessAdminPanel';section.className='card';section.style.marginTop='10px';section.innerHTML='<div class="request-head"><div><h3>Заявки на доступ</h3><div class="muted">FREE invite-only: персональная одноразовая ссылка, срок 7 дней, привязка к email.</div></div><button id="accessRefresh">Обновить</button></div><div id="accessStats" class="access-admin-stats" style="margin-top:10px"></div><div id="accessRequests"><div class="muted" style="margin-top:10px">Загрузка…</div></div>';dashboard.appendChild(section);document.getElementById('accessRefresh').onclick=load;}
  function setBusy(v){busy=v;document.querySelectorAll('#accessAdminPanel button').forEach(el=>el.disabled=v)}
  async function invoke(body){const {data,error}=await sb.functions.invoke(ENDPOINT,{body});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Access request failed');return data}
  function render(){mount();const counts={pending:0,invited:0,activated:0,rejected:0,expired:0};state.forEach(r=>counts[r.status]=(counts[r.status]||0)+1);document.getElementById('accessStats').innerHTML=[['Ожидают',counts.pending],['Приглашены',counts.invited],['Активированы',counts.activated],['Отклонены/истекли',(counts.rejected||0)+(counts.expired||0)]].map(([l,v])=>`<div class="access-admin-stat"><span>${l}</span><b>${v}</b></div>`).join('');const root=document.getElementById('accessRequests');root.innerHTML=state.length?state.map((r,i)=>`<article class="access-request"><div class="access-request-head"><div><b>${safe(r.email)}</b><div class="muted">${safe(r.locale||'ru')} · заявка ${when(r.created_at)}</div></div><div><b>${safe(r.status)}</b><div class="muted">${r.invite_expires_at?'до '+when(r.invite_expires_at):''}</div></div></div><div class="access-request-actions">${r.status!=='activated'?`<button class="gold" data-invite="${i}">${r.status==='invited'?'Перевыпустить ссылку':'Создать ссылку'}</button>`:''}${!['activated','rejected'].includes(r.status)?`<button data-reject="${i}">Отклонить</button>`:''}</div><div id="access-link-${i}"></div></article>`).join(''):'<div class="muted" style="margin-top:10px">Заявок пока нет.</div>';root.querySelectorAll('[data-invite]').forEach(b=>b.onclick=()=>createInvite(Number(b.dataset.invite)));root.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reject(Number(b.dataset.reject)))}
  async function load(){mount();if(busy)return;setBusy(true);try{const data=await invoke({action:'list'});state=data.requests||[];render()}catch(error){message(error.message||error,true)}finally{setBusy(false)}}
  async function createInvite(i){const r=state[i];if(!r||busy)return;setBusy(true);try{const data=await invoke({action:'invite',request_id:r.id});const box=document.getElementById(`access-link-${i}`);box.innerHTML=`<div class="access-link"><b>Персональная ссылка создана</b><div class="muted">Отправьте её только ${safe(data.email)}. После активации повторно использовать нельзя.</div><input id="invite-copy-${i}" readonly value="${safe(data.invite_url)}"><div class="access-request-actions"><button data-copy="${i}">Копировать ссылку</button></div></div>`;box.querySelector('[data-copy]').onclick=async()=>{const input=document.getElementById(`invite-copy-${i}`);try{await navigator.clipboard.writeText(input.value);message('Ссылка скопирована.')}catch{input.select();document.execCommand('copy');message('Ссылка скопирована.')}};message('Одноразовая ссылка создана.');await refreshStateOnly()}catch(error){message(error.message||error,true)}finally{setBusy(false)}}
  async function refreshStateOnly(){try{const data=await invoke({action:'list'});state=data.requests||[]}catch{}}
  async function reject(i){const r=state[i];if(!r||busy)return;setBusy(true);try{await invoke({action:'reject',request_id:r.id});message('Заявка отклонена.');await load()}catch(error){message(error.message||error,true)}finally{setBusy(false)}}
  mount();document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(load,0));sb.auth.onAuthStateChange((_event,session)=>{if(session)setTimeout(load,0);else document.getElementById('accessAdminPanel')?.remove()});sb.auth.getSession().then(({data})=>{if(data.session)setTimeout(load,0)});
})();