'use strict';
(() => {
  const $=id=>document.getElementById(id),safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  let mounted=false,busy=false,state=null;
  function notify(value,bad=false){if(typeof message==='function')message(value,bad);}
  function when(value){return value?new Date(value).toLocaleString():'—';}
  function compact(value){const text=JSON.stringify(value||{});return text.length>360?text.slice(0,357)+'…':text;}
  function mount(){
    if(mounted||!$('dashboard'))return;mounted=true;
    const style=document.createElement('style');style.id='adminAuditStyles';style.textContent='.audit-head{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.audit-filters{display:flex;gap:7px;flex-wrap:wrap}.audit-filters select,.audit-filters button{min-height:38px}.audit-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.audit-stat{padding:10px;background:var(--p2);border:1px solid var(--line);border-radius:8px}.audit-stat span{display:block;color:var(--m);font-size:9px;text-transform:uppercase}.audit-stat b{display:block;font-size:18px;margin-top:5px}.audit-table{overflow:auto;max-height:520px}.audit-table table{min-width:1250px}.audit-json{font:10px ui-monospace,monospace;white-space:pre-wrap;word-break:break-word;max-width:300px}.audit-high{color:#ffc4cd}.audit-medium{color:#ffe58f}@media(max-width:800px){.audit-stats{grid-template-columns:1fr 1fr}.audit-filters>*{flex:1}}@media(max-width:480px){.audit-stats{grid-template-columns:1fr}}';document.head.appendChild(style);
    const section=document.createElement('section');section.id='adminAuditSection';section.className='card';section.style.marginTop='10px';section.innerHTML='<div class="audit-head"><div><h3>Журнал критических действий</h3><div class="muted">Неизменяемый серверный аудит тарифов, подписок, billing, поддержки и удаления аккаунтов.</div></div><div class="audit-filters"><select id="auditAction"><option value="">Все действия</option><option value="update">UPDATE</option><option value="delete">DELETE</option></select><select id="auditEntity"><option value="">Все объекты</option><option value="crypto_subscriptions">Подписки</option><option value="crypto_plan_prices">Цены</option><option value="crypto_plan_requests">Заявки</option><option value="crypto_support_tickets">Поддержка</option><option value="crypto_billing_events">Billing events</option><option value="crypto_billing_anomalies">Billing anomalies</option><option value="crypto_billing_provider_adapters">Провайдеры</option><option value="crypto_account_deletion_requests">Удаление аккаунта</option><option value="crypto_user_profiles">Роли</option></select><button id="auditRefresh">Обновить</button></div></div><div id="auditStats" class="audit-stats"></div><div id="auditRows" class="audit-table"></div>';
    $('dashboard').appendChild(section);$('auditRefresh').onclick=load;$('auditAction').onchange=load;$('auditEntity').onchange=load;
  }
  function setBusy(value){busy=value;document.querySelectorAll('#adminAuditSection button,#adminAuditSection select').forEach(node=>node.disabled=value);}
  function render(){
    mount();const counts=state?.counts||{},rows=Array.isArray(state?.rows)?state.rows:[];
    $('auditStats').innerHTML=[['24 часа',counts.last_24h],['Высокий риск',counts.high_24h],['Admin RPC',counts.admin_24h],['Service',counts.service_24h]].map(([label,value])=>`<div class="audit-stat"><span>${safe(label)}</span><b>${Number(value||0)}</b></div>`).join('');
    $('auditRows').innerHTML=rows.length?`<table aria-label="Журнал критических административных действий"><thead><tr><th>Дата</th><th>Актор</th><th>Источник</th><th>Риск</th><th>Действие</th><th>Объект</th><th>ID</th><th>Было</th><th>Стало</th><th>Correlation</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${when(row.created_at)}</td><td>${safe(row.actor_email||row.actor_name||row.actor_role||'service')}</td><td>${safe(row.source)}</td><td class="${row.severity==='high'||row.severity==='critical'?'audit-high':row.severity==='medium'?'audit-medium':''}">${safe(row.severity)}</td><td>${safe(row.action)}</td><td>${safe(row.entity_type)}</td><td>${safe(row.entity_id||'—')}</td><td class="audit-json">${safe(compact(row.old_state))}</td><td class="audit-json">${safe(compact(row.new_state))}</td><td class="audit-json">${safe(row.correlation_id||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="muted">Записей по выбранному фильтру нет.</div>';
  }
  async function load(){if(busy)return;mount();if($('dashboard')?.classList.contains('hide'))return;setBusy(true);try{const {data,error}=await sb.rpc('get_crypto_admin_audit',{p_limit:150,p_action:$('auditAction')?.value||null,p_entity_type:$('auditEntity')?.value||null});if(error)throw error;state=data||{};render();}catch(error){notify(error.message||error,true);}finally{setBusy(false);}}
  function boot(){mount();if(!$('dashboard')?.classList.contains('hide')&&!state)load();}
  new MutationObserver(boot).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
  $('refresh')?.addEventListener('click',()=>setTimeout(load,0));sb.auth.onAuthStateChange((_event,current)=>{state=null;if(current)setTimeout(load,0);});boot();
})();