'use strict';
(() => {
  const ENDPOINT='https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-lab-v79-commercial';
  const LIQPAY_ENDPOINT='https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-lab-v79-liqpay-sandbox';
  const COPY={
    ru:{title:'Доступ CRYPTO LAB',text:'Платные тарифы публично не запущены.',pilotTitle:'Friends & Family · Sandbox',pilotText:'Закрытый тест для друзей и семьи. Тестовый контур не списывает реальные деньги.',legal:'Юридическое согласие',accepted:'Актуальные документы приняты.',required:'Примите все актуальные документы.',accept:'Принять документы',plans:'Тарифы',note:'Комментарий к заявке — необязательно',request:'Запросить',cancel:'Отменить заявку',pending:'Ожидает обработки',unconfigured:'Публичная оплата выключена',saved:'Согласие сохранено.',requested:'Заявка создана.',cancelled:'Заявка отменена.',error:'Сервис временно недоступен.',manual:'Создать sandbox-заказ',liqpay:'LiqPay Sandbox',liqpayMissing:'LiqPay Sandbox: нужны test merchant keys',order:'Последний sandbox-заказ',noOrder:'Sandbox-заказов ещё нет',created:'Sandbox-заказ создан. Подтверждение выполняется администратором.',redirect:'Переход в LiqPay Sandbox…',docs:{terms:'Условия использования',privacy:'Конфиденциальность',refund:'Политика возвратов',risk:'Раскрытие рисков'}},
    uk:{title:'Доступ CRYPTO LAB',text:'Платні тарифи публічно не запущені.',pilotTitle:'Friends & Family · Sandbox',pilotText:'Закритий тест для друзів і родини. Тестовий контур не списує реальні кошти.',legal:'Юридична згода',accepted:'Актуальні документи прийнято.',required:'Прийміть усі актуальні документи.',accept:'Прийняти документи',plans:'Тарифи',note:'Коментар до заявки — необов’язково',request:'Запросити',cancel:'Скасувати заявку',pending:'Очікує обробки',unconfigured:'Публічну оплату вимкнено',saved:'Згоду збережено.',requested:'Заявку створено.',cancelled:'Заявку скасовано.',error:'Сервіс тимчасово недоступний.',manual:'Створити sandbox-замовлення',liqpay:'LiqPay Sandbox',liqpayMissing:'LiqPay Sandbox: потрібні test merchant keys',order:'Останнє sandbox-замовлення',noOrder:'Sandbox-замовлень ще немає',created:'Sandbox-замовлення створено. Підтвердження виконує адміністратор.',redirect:'Перехід у LiqPay Sandbox…',docs:{terms:'Умови використання',privacy:'Конфіденційність',refund:'Політика повернень',risk:'Розкриття ризиків'}},
    en:{title:'CRYPTO LAB access',text:'Paid plans are not publicly launched.',pilotTitle:'Friends & Family · Sandbox',pilotText:'Closed testing for friends and family. The sandbox flow does not move real money.',legal:'Legal consent',accepted:'Current documents accepted.',required:'Accept every current document.',accept:'Accept documents',plans:'Plans',note:'Optional request note',request:'Request',cancel:'Cancel request',pending:'Pending review',unconfigured:'Public payments are disabled',saved:'Consent saved.',requested:'Request created.',cancelled:'Request cancelled.',error:'Service is temporarily unavailable.',manual:'Create sandbox order',liqpay:'LiqPay Sandbox',liqpayMissing:'LiqPay Sandbox: test merchant keys required',order:'Latest sandbox order',noOrder:'No sandbox orders yet',created:'Sandbox order created. An administrator confirms it.',redirect:'Opening LiqPay Sandbox…',docs:{terms:'Terms of Use',privacy:'Privacy Notice',refund:'Refund Policy',risk:'Risk Disclosure'}}
  };
  let state=null,busy=false,mounted=false,liqpayReady=false;
  const t=()=>COPY[typeof lang==='string'?lang:'ru']||COPY.ru;
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const money=(minor,currency)=>new Intl.NumberFormat(lang==='uk'?'uk-UA':lang==='en'?'en-US':'ru-RU',{style:'currency',currency:currency||'USD',minimumFractionDigits:0,maximumFractionDigits:2}).format(Number(minor||0)/100);
  const say=(value,bad=false)=>typeof show==='function'&&show(value,bad?'bad':'ok');
  async function currentSession(){const {data}=await client.auth.getSession();return data.session;}
  async function api(method='GET',body=null,endpoint=ENDPOINT){const active=await currentSession();if(!active)throw new Error('Authentication required');const response=await fetch(endpoint,{method,headers:{Authorization:`Bearer ${active.access_token}`,apikey:typeof PUBLISHABLE_KEY==='string'?PUBLISHABLE_KEY:'','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||t().error);error.code=data.code;throw error;}return data;}
  function mount(){if(mounted||!document.getElementById('plans'))return;mounted=true;const style=document.createElement('style');style.id='commercialStyles';style.textContent='.commercial-grid{display:grid;grid-template-columns:minmax(280px,.9fr) minmax(0,1.1fr);gap:10px}.legal-row{display:flex;align-items:flex-start;gap:8px;padding:8px 0;border-top:1px solid var(--line)}.legal-row:first-child{border-top:0}.legal-row input{width:auto;margin-top:3px}.commercial-plan,.pilot-box{padding:10px;border:1px solid var(--line);border-radius:9px;background:var(--p2);margin-top:8px}.pilot-box{border-color:#0ecb8155;background:#0ecb810b}.commercial-plan-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.commercial-status{font-size:10px;font-weight:850}.commercial-status.ready{color:#a7f3d0}.commercial-status.blocked{color:#ffc4cd}.commercial-note{width:100%;min-height:64px;resize:vertical;margin-top:9px}.pilot-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.pilot-order{font:10px ui-monospace,monospace;color:var(--muted);margin-top:8px;word-break:break-word}@media(max-width:760px){.commercial-grid{grid-template-columns:1fr}.pilot-actions button{width:100%;min-height:42px}}';document.head.appendChild(style);const section=document.createElement('section');section.id='commercialCenter';section.className='card';section.style.marginTop='10px';section.innerHTML='<h3 id="commercialTitle"></h3><p id="commercialText" class="muted"></p><div id="pilotCenter"></div><div class="commercial-grid"><div><h3 id="commercialLegalTitle"></h3><div id="commercialLegal"></div></div><div><h3 id="commercialPlansTitle"></h3><div id="commercialPlans"></div></div></div>';document.getElementById('plans').after(section);}
  function removeLegacyButtons(){document.querySelectorAll('#plans .plan > button.btn.gold').forEach(button=>button.remove());}
  function priceFor(plan){const prices=Array.isArray(state?.prices)?state.prices:[];return prices.find(item=>item.plan===plan&&item.interval==='month')||prices.find(item=>item.plan===plan);}
  function canPlan(plan,pilot){return pilot?.max_plan==='PRO'||pilot?.max_plan===plan;}
  function renderPilot(){const c=t(),box=document.getElementById('pilotCenter'),pilot=state?.friends_family_pilot;if(!box)return;if(!pilot?.eligible){box.innerHTML='';return;}const order=pilot.latest_order;box.innerHTML=`<div class="pilot-box"><div class="commercial-plan-head"><div><b>${safe(c.pilotTitle)}</b><div class="muted">${safe(c.pilotText)}</div></div><span class="commercial-status ready">ALLOWLIST</span></div><div class="pilot-actions">${['BASIC','PRO'].filter(plan=>canPlan(plan,pilot)).map(plan=>{const p=priceFor(plan);return `<button class="btn gold" data-pilot-manual="${plan}" ${state?.has_current_acceptance?'':'disabled'}>${safe(c.manual)} · ${plan} ${p?money(p.amount_minor,p.currency):''}</button><button class="btn" data-pilot-liqpay="${plan}" ${state?.has_current_acceptance&&liqpayReady?'':'disabled'}>${safe(liqpayReady?c.liqpay:c.liqpayMissing)} · ${plan}</button>`;}).join('')}</div><div class="pilot-order"><b>${safe(c.order)}:</b> ${order?`${safe(order.plan)} · ${safe(order.provider)} · ${safe(order.status)} · ${money(order.amount_minor,order.currency)}`:safe(c.noOrder)}</div></div>`;document.querySelectorAll('[data-pilot-manual]').forEach(button=>button.addEventListener('click',()=>pilotManual(button.dataset.pilotManual)));document.querySelectorAll('[data-pilot-liqpay]').forEach(button=>button.addEventListener('click',()=>pilotLiqPay(button.dataset.pilotLiqpay)));}
  function render(){mount();removeLegacyButtons();if(!mounted)return;const c=t();document.getElementById('commercialTitle').textContent=c.title;document.getElementById('commercialText').textContent=c.text;document.getElementById('commercialLegalTitle').textContent=c.legal;document.getElementById('commercialPlansTitle').textContent=c.plans;const documents=Array.isArray(state?.documents)?state.documents:[],accepted=new Map((state?.accepted||[]).map(item=>[item.key,item.version]));const legal=document.getElementById('commercialLegal');legal.innerHTML=documents.length?documents.map(doc=>{const current=accepted.get(doc.key)===doc.version;return `<label class="legal-row"><input type="checkbox" data-legal="${safe(doc.key)}" ${current?'checked disabled':''}><span><a href="${safe(doc.url)}?lang=${encodeURIComponent(lang)}" target="_blank" rel="noopener">${safe(c.docs[doc.key]||doc.key)}</a><div class="muted">v${safe(doc.version)} · <span class="commercial-status ${current?'ready':'blocked'}">${current?c.accepted:c.required}</span></div></span></label>`;}).join(''):'<div class="muted">—</div>';if(!state?.has_current_acceptance&&documents.length)legal.insertAdjacentHTML('beforeend',`<button class="btn gold" id="acceptLegalBtn" style="margin-top:8px">${safe(c.accept)}</button>`);const pending=state?.pending_request,prices=Array.isArray(state?.prices)?state.prices:[];document.getElementById('commercialPlans').innerHTML=['BASIC','PRO'].map(plan=>{const price=prices.find(item=>item.plan===plan&&item.interval==='month')||prices.find(item=>item.plan===plan),isPending=pending?.requested_plan===plan;return `<div class="commercial-plan"><div class="commercial-plan-head"><b>${plan}</b><span class="commercial-status blocked">${price?money(price.amount_minor,price.currency):c.unconfigured}</span></div><div class="muted">${safe(c.unconfigured)}</div>${isPending?`<p class="muted">${safe(c.pending)}</p><button class="btn" id="cancelPlanRequest">${safe(c.cancel)}</button>`:`<textarea class="commercial-note" data-plan-note="${plan}" maxlength="500" placeholder="${safe(c.note)}"></textarea><button class="btn" data-request-plan="${plan}" ${state?.has_current_acceptance?'':'disabled'}>${safe(c.request)} ${plan}</button>`}</div>`;}).join('');renderPilot();document.getElementById('acceptLegalBtn')?.addEventListener('click',acceptLegal);document.querySelectorAll('[data-request-plan]').forEach(button=>button.addEventListener('click',()=>requestPlan(button.dataset.requestPlan)));document.getElementById('cancelPlanRequest')?.addEventListener('click',cancelRequest);}
  function setBusy(value){busy=value;document.querySelectorAll('#commercialCenter button,#commercialCenter input,#commercialCenter textarea').forEach(el=>el.disabled=value||(el.dataset?.legal&&el.defaultChecked));}
  async function loadLiqPay(){liqpayReady=false;try{const data=await api('GET',null,LIQPAY_ENDPOINT);liqpayReady=data?.configured===true&&data?.mode==='sandbox'&&data?.real_money===false;}catch{} }
  async function load(){if(busy)return;mount();setBusy(true);try{const [data]=await Promise.all([api(),loadLiqPay()]);state=data.state||{};render();}catch(error){say(error.message||t().error,true);}finally{setBusy(false);}}
  async function acceptLegal(){if(busy)return;const docs=(state?.documents||[]);if(!docs.length)return;const all=docs.every(doc=>document.querySelector(`[data-legal="${CSS.escape(doc.key)}"]`)?.checked);if(!all)return say(t().required,true);setBusy(true);try{const data=await api('POST',{action:'accept_legal',locale:lang,documents:docs.map(doc=>({key:doc.key,version:doc.version}))});state=data.state||{};render();say(t().saved);}catch(error){say(error.message||t().error,true);}finally{setBusy(false);}}
  async function requestPlan(plan){if(busy||!state?.has_current_acceptance)return say(t().required,true);const note=document.querySelector(`[data-plan-note="${plan}"]`)?.value.trim()||'';setBusy(true);try{const data=await api('POST',{action:'request_plan',plan,note});state=data.state||{};render();say(t().requested);}catch(error){say(error.message||t().error,true);}finally{setBusy(false);}}
  async function cancelRequest(){if(busy)return;setBusy(true);try{const data=await api('POST',{action:'cancel_request'});state=data.state||{};render();say(t().cancelled);}catch(error){say(error.message||t().error,true);}finally{setBusy(false);}}
  async function pilotManual(plan){if(busy)return;setBusy(true);try{const data=await api('POST',{action:'pilot_checkout',plan,provider:'manual'});state=data.state||{};render();say(t().created);}catch(error){say(error.message||t().error,true);}finally{setBusy(false);}}
  async function pilotLiqPay(plan){if(busy||!liqpayReady)return;setBusy(true);try{const data=await api('POST',{action:'checkout',plan,language:lang==='en'?'en':'uk'},LIQPAY_ENDPOINT);say(t().redirect);const form=document.createElement('form');form.method='POST';form.action=data.checkout_endpoint;form.style.display='none';for(const [name,value] of Object.entries({data:data.data,signature:data.signature})){const input=document.createElement('input');input.type='hidden';input.name=name;input.value=String(value);form.appendChild(input);}document.body.appendChild(form);form.submit();}catch(error){say(error.message||t().error,true);setBusy(false);}}
  const observer=new MutationObserver(()=>{if(account&&session){mount();removeLegacyButtons();if(!state)load();}});observer.observe(document.documentElement,{childList:true,subtree:true});client.auth.onAuthStateChange((_event,current)=>{if(current){state=null;setTimeout(load,0);}else{state=null;document.getElementById('commercialCenter')?.remove();mounted=false;}});document.getElementById('lang')?.addEventListener('change',()=>setTimeout(render,0));if(account&&session)load();
})();