'use strict';
const CACHE='crypto-lab-v79-7930-free20';
// Legacy release markers retained for contract history: crypto-lab-v79-7930-pwa2 crypto-lab-v79-7930-pwa3 crypto-lab-v79-7930-free1 crypto-lab-v79-7930-free2 crypto-lab-v79-7930-free3 crypto-lab-v79-7930-free4 crypto-lab-v79-7930-free5 crypto-lab-v79-7930-free6 crypto-lab-v79-7930-free7 crypto-lab-v79-7930-free8 crypto-lab-v79-7930-free9 crypto-lab-v79-7930-free10 crypto-lab-v79-7930-free11 crypto-lab-v79-7930-free12 crypto-lab-v79-7930-free13 crypto-lab-v79-7930-free14 crypto-lab-v79-7930-free15 crypto-lab-v79-7930-free16 crypto-lab-v79-7930-free17 crypto-lab-v79-7930-free18 crypto-lab-v79-7930-free19.
const SHELL=['./','./index.html','./app.html','./app.css','./app.js','./route-merge.js','./news-extension.js','./news.html','./public-free-home.js','./home-intelligence.js','./home-chart.js','./access-gate.js','./app-extension.js','./support-extension.js','./commercial-extension.js','./accessibility.js','./module-accessibility.js','./platform.css','./module-mobile.css','./manifest.webmanifest','./icon.svg','./offline.html','./chart.html','./chart-interactions.js','./chart-analysis-tools.js','./chart-analysis-hook.js','./chart-visual-upgrades.js','./chart-fib-scale.js','./chart-onchain.js','./portfolio.html','./calculator.html','./backtest.html','./backtest-history.js','./scanner.html','./scanner-actions.js','./ai.html','./journal.html','./journal.js','./journal-import.js','./journal-analytics.js','./education.html','./account.html','./account-actions.js','./session-security.js','./free-access-ui.js','./registration-consent.js','./auth-gateway.js','./recovery.html','./support.html','./admin.html','./admin-health.js','./admin-incidents.js','./admin-slo.js','./admin-ops-summary.js','./admin-integrity.js','./admin-drift.js','./admin-maintenance.js','./admin-deletions.js','./admin-support.js','./admin-access.js','./admin-audit.js','./admin-session-security.js','./admin-readiness.js','./admin-telemetry.js','./admin-ai-telemetry.js','./legal.js','./privacy.html','./terms.html','./risk-disclosure.html','./refund.html'];
const NETWORK_FIRST=new Set(['app.html','route-merge.js','news-extension.js','news.html','access-gate.js','account.html','account-actions.js','registration-consent.js','auth-gateway.js','free-access-ui.js','recovery.html','public-free-home.js','home-intelligence.js','home-chart.js','platform.css','support-extension.js','support.html','admin-support.js','admin-access.js','education.html','app-extension.js','commercial-extension.js','chart.html','chart-interactions.js','chart-analysis-tools.js','chart-analysis-hook.js','chart-visual-upgrades.js','chart-fib-scale.js','chart-onchain.js','scanner.html','ai.html','backtest.html']);
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('crypto-lab-v79-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CLEAR_OLD_CACHES')event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))))});
function isApi(url){return url.hostname.includes('supabase.co')||url.hostname.includes('binance.com')||url.hostname.includes('binance.vision')||url.hostname.includes('jsdelivr.net')||url.hostname.includes('challenges.cloudflare.com')}
function networkFirst(url){return NETWORK_FIRST.has(url.pathname.split('/').pop()||'')}
async function cached(request){return caches.match(request,{ignoreSearch:true})}
async function store(request,response){if(response?.ok){const copy=response.clone();await caches.open(CACHE).then(cache=>cache.put(request,copy))}return response}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(isApi(url)||url.origin!==self.location.origin)return;if(req.mode==='navigate'){event.respondWith(fetch(req).then(response=>store(req,response)).catch(async()=>{const hit=await cached(req);if(hit)return hit;if(url.pathname.endsWith('/v79/')||url.pathname.endsWith('/v79/index.html')||url.pathname.endsWith('/v79/app.html')){const shell=await caches.match('./app.html',{ignoreSearch:true});if(shell)return shell;}return caches.match('./offline.html',{ignoreSearch:true});}));return;}if(networkFirst(url)){event.respondWith(fetch(req,{cache:'no-store'}).then(response=>store(req,response)).catch(()=>cached(req).then(hit=>hit||caches.match('./offline.html',{ignoreSearch:true}))));return;}event.respondWith(cached(req).then(hit=>hit||fetch(req).then(response=>store(req,response)).catch(()=>caches.match('./offline.html',{ignoreSearch:true}))));});
