import json,subprocess
from datetime import datetime,timezone
from pathlib import Path
R=Path('.'); V='20260805105743'; N='restore_exact_owner_three_network_authority_after_104812_stale_cycle'; S=f'supabase/migrations/{V}_{N}.sql'; SV='20260805104812'; SN='authoritative_candidate_only_recovery_after_103945'; E='Три сети утверждаю.'; H='57458fbfe9da805c8dc8bec7ad2d8500516ca4568c35903565402aed62d848be'; NET=['TRON','BSC','SOLANA']; ST='4a278c891d37b3760ec1ac988690ea9ad587b24e'; NOW=datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00','Z'); C=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(); A={'version':V,'name':N,'source':S,'source_commit':C}
def load(p): return json.loads((R/p).read_text(encoding='utf-8'))
def save(p,d): (R/p).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

p='docs/release-manifests/crypto-lab-v79-onchain-payments.json'; d=load(p); d.update(updated_at=NOW,status='disabled_pending_remaining_decisions',activation_allowed=False,publication_allowed=False,approved_networks=NET,owner_network_approval_recorded=True,owner_provider_approval_recorded=False,authoritative_migration=A); d['owner_decision'].update(decision_code='ONCHAIN_THREE_NETWORK_SELECTION',decision_text_exact=E,decision_hash_sha256=H,decision_scope='network_selection_only',network_activation_authorized=False,active=True,source_channel='owner_chat')
for x in d['networks']: x.update(approved_by_owner=True,active=False)
d['runtime_state'].update(approved_network_count=3,active_network_count=0,selected_asset_count=0,enabled_network_asset_count=0,active_price_count=0,receiving_address_count=0,invoice_count=0,transaction_claim_count=0,chain_observation_count=0,auth_user_count=0,registration_attempt_count=0,recovery_attempt_count=0,provider_desired_mode='disabled',provider_lifecycle_status='draft',checkout_enabled=False,webhook_enabled=False,recurring_enabled=False,refunds_enabled=False)
d['provenance_incident'].update(overlapping_automation_runs_confirmed=True,recurring_automation_disabled=True,exact_owner_text_preserved=True,stale_candidate_only_migration_superseded=SV,latest_stale_candidate_only_migration=f'{SV}_{SN}',historical_false_migrations_preserved_for_audit=True,autonomous_owner_decision_bypass_available=False); d['repository_sync'].update(release_manifest_aligned=True,foundation_workflow_aligned=True,stale_candidate_only_artifacts_removed=True,automation_resume_allowed=False); save(p,d); runtime=d['runtime_state']

p='docs/release-manifests/crypto-lab-v79-payment-sandbox-matrix.json'; m=load(p); m.update(updated_at=NOW,mode='disabled',activation_allowed=False,publication_allowed=False,approved_networks=NET,owner_network_approval_recorded=True,settlement_asset='pending',authoritative_migration=A,runtime_state=runtime,scenario_count=len(m['scenarios'])); assert m['scenario_count']==29==len({x['code'] for x in m['scenarios']}); save(p,m)

p='docs/release-manifests/crypto-lab-v79-owner-network-decision.json'; o=load(p); o.update(updated_at=NOW,decision_code='ONCHAIN_THREE_NETWORK_SELECTION',decision_text_exact=E,decision_hash_sha256=H,decision_scope='network_selection_only',active=True,immutable=True,settlement_asset='pending',activation_allowed=False,publication_allowed=False,checkout_enabled=False,webhook_enabled=False,recurring_enabled=False,refunds_enabled=False,authoritative_migration=A,stable_root_v78_sha=ST)
for x in o['approved_networks']: x.update(approved_by_owner=True,active=False)
save(p,o)

p='docs/release-manifests/crypto-lab-v79-7930.json'; r=load(p); r['updated_at']=NOW; z={x.get('version'):x for x in r.setdefault('migrations',[])}; z.setdefault(SV,{'version':SV,'name':SN}).update(version=SV,name=SN); z[V]=dict(A); r['migrations']=sorted(z.values(),key=lambda x:(x.get('version',''),x.get('name',''))); q=r.setdefault('operational_hardening',{}); q.update(payment_provider_status='in_progress_disabled',payment_sandbox_matrix_schema_version=10,automatic_wallet_debit=False,registration_enabled=False,recovery_enabled=False,v79_publication_authorized=False,onchain_authoritative_migration_version=V,onchain_authoritative_migration_name=N,onchain_authoritative_migration_source_commit=C,onchain_latest_stale_candidate_only_migration=f'{SV}_{SN}',onchain_latest_repair_migration_version=V,onchain_approved_networks=NET,onchain_approved_network_count=3,onchain_active_network_count=0,onchain_selected_asset_count=0,onchain_enabled_network_asset_count=0,onchain_active_price_count=0,onchain_receiving_address_count=0,onchain_invoice_count=0,onchain_chain_observation_count=0,onchain_transaction_claim_count=0,onchain_active_owner_decision_record_count=1,onchain_effective_authority_event_count=1,onchain_effective_false_supersession_count=0,onchain_owner_approval_recorded=True,onchain_owner_network_approval_recorded=True,onchain_owner_provider_approval_recorded=False,onchain_network_activation_authorized=False,onchain_owner_approval_fail_closed=True,onchain_automatic_entitlement_enabled=False,onchain_automatic_wallet_debit=False,onchain_settlement_asset='pending',onchain_provider_mode='disabled',onchain_provider_lifecycle='draft',onchain_checkout_enabled=False,onchain_webhook_enabled=False,onchain_recurring_enabled=False,onchain_refunds_enabled=False,onchain_sandbox_scenario_count=29,direct_onchain_payment_activation_allowed=False,onchain_concurrency_race_confirmed=True,onchain_recurring_automation_disabled=True,onchain_automation_resume_allowed=False,onchain_false_supersession_invalidated=True); save(p,r)

rep={'20260805103945_restore_exact_owner_three_network_authority_after_103527_stale_cycle.sql':f'{V}_{N}.sql','20260805103945':V,'restore_exact_owner_three_network_authority_after_103527_stale_cycle':N}
for p in ['scripts/v79_validate_onchain_foundation.py','.github/workflows/v79-onchain-payment-foundation-validation.yml','.github/workflows/v79-owner-decision-failclosed-validation.yml','.github/workflows/v79-release-manifest-contract.yml']:
 t=(R/p).read_text(encoding='utf-8')
 for a,b in rep.items(): t=t.replace(a,b)
 (R/p).write_text(t,encoding='utf-8')
print('Synchronized exact owner-approved inactive state',V)
