create table if not exists public.crypto_commercial_funnel_events (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  anonymous_session_hash text null check (anonymous_session_hash is null or anonymous_session_hash ~ '^[0-9a-f]{64}$'),
  event_type text not null check (event_type in ('landing_view','pricing_view','signup_started','signup_confirmed','plan_requested','checkout_started','payment_verified','subscription_activated','subscription_renewed','subscription_cancelled','support_opened')),
  source text not null default 'unknown' check (length(source) between 1 and 80),
  campaign_code text null check (campaign_code is null or campaign_code ~ '^[A-Za-z0-9_-]{1,64}$'),
  referral_code text null check (referral_code is null or referral_code ~ '^[A-Za-z0-9_-]{3,32}$'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (user_id is not null or anonymous_session_hash is not null)
);
create index if not exists crypto_commercial_funnel_events_time_idx on public.crypto_commercial_funnel_events(occurred_at desc);
create index if not exists crypto_commercial_funnel_events_user_idx on public.crypto_commercial_funnel_events(user_id,occurred_at desc) where user_id is not null;
create index if not exists crypto_commercial_funnel_events_type_idx on public.crypto_commercial_funnel_events(event_type,occurred_at desc);

create table if not exists public.crypto_referral_program_config (
  singleton boolean primary key default true check (singleton),
  enabled boolean not null default false,
  activation_authorized boolean not null default false,
  reward_model text not null default 'owner_decision_required' check (reward_model in ('owner_decision_required','fixed','percent')),
  reward_value numeric null check (reward_value is null or reward_value >= 0),
  reward_currency text null check (reward_currency is null or reward_currency ~ '^[A-Z]{3,10}$'),
  attribution_window_days integer null check (attribution_window_days is null or attribution_window_days between 1 and 365),
  terms_version text null,
  metadata jsonb not null default '{"state":"prepared_inactive","payouts_enabled":false}'::jsonb check (jsonb_typeof(metadata)='object'),
  updated_at timestamptz not null default now(),
  check (not enabled or activation_authorized),
  check (not enabled or reward_model <> 'owner_decision_required'),
  check (not enabled or attribution_window_days is not null),
  check (reward_model='owner_decision_required' or reward_value is not null)
);
insert into public.crypto_referral_program_config(singleton) values(true) on conflict(singleton) do nothing;

create table if not exists public.crypto_referral_codes (
  code text primary key check (code ~ '^[A-Za-z0-9_-]{3,32}$'),
  owner_user_id uuid null,
  partner_label text not null check (length(btrim(partner_label)) between 1 and 120),
  status text not null default 'draft' check (status in ('draft','active','disabled')),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crypto_referral_attributions (
  user_id uuid primary key,
  referral_code text not null references public.crypto_referral_codes(code),
  source text not null default 'registration' check (source in ('registration','account','checkout')),
  first_touch_at timestamptz not null default now(),
  attributed_at timestamptz not null default now(),
  locked boolean not null default true,
  evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(evidence)='object')
);
create index if not exists crypto_referral_attributions_code_idx on public.crypto_referral_attributions(referral_code,attributed_at desc);

alter table public.crypto_commercial_funnel_events enable row level security;
alter table public.crypto_referral_program_config enable row level security;
alter table public.crypto_referral_codes enable row level security;
alter table public.crypto_referral_attributions enable row level security;

revoke all on table public.crypto_commercial_funnel_events from public,anon,authenticated;
revoke all on table public.crypto_referral_program_config from public,anon,authenticated;
revoke all on table public.crypto_referral_codes from public,anon,authenticated;
revoke all on table public.crypto_referral_attributions from public,anon,authenticated;
grant select,insert on table public.crypto_commercial_funnel_events to service_role;
grant select,insert,update on table public.crypto_referral_program_config to service_role;
grant select,insert,update on table public.crypto_referral_codes to service_role;
grant select,insert on table public.crypto_referral_attributions to service_role;

create policy crypto_commercial_funnel_events_deny_anon on public.crypto_commercial_funnel_events for all to anon using(false) with check(false);
create policy crypto_commercial_funnel_events_deny_authenticated on public.crypto_commercial_funnel_events for all to authenticated using(false) with check(false);
create policy crypto_referral_program_config_deny_anon on public.crypto_referral_program_config for all to anon using(false) with check(false);
create policy crypto_referral_program_config_deny_authenticated on public.crypto_referral_program_config for all to authenticated using(false) with check(false);
create policy crypto_referral_codes_deny_anon on public.crypto_referral_codes for all to anon using(false) with check(false);
create policy crypto_referral_codes_deny_authenticated on public.crypto_referral_codes for all to authenticated using(false) with check(false);
create policy crypto_referral_attributions_deny_anon on public.crypto_referral_attributions for all to anon using(false) with check(false);
create policy crypto_referral_attributions_deny_authenticated on public.crypto_referral_attributions for all to authenticated using(false) with check(false);

create or replace function private.crypto_assert_commercial_metadata_safe(p_value jsonb)
returns void language plpgsql immutable set search_path=pg_catalog,pg_temp as $$
begin
  if p_value is null or jsonb_typeof(p_value)<>'object' or length(p_value::text)>16000 then
    raise exception 'Invalid commercial metadata' using errcode='22023';
  end if;
  if lower(p_value::text) ~ '"(private_key|privatekey|seed|seed_phrase|seedphrase|mnemonic|password|wallet_password|walletpassword|authorization|access_token|refresh_token|api_key|secret|email|ip_address|raw_ip)"[[:space:]]*:' then
    raise exception 'Sensitive commercial metadata rejected' using errcode='22023';
  end if;
end;
$$;

create or replace function private.service_record_crypto_funnel_event(
  p_user_id uuid,
  p_session_hash text,
  p_event_type text,
  p_source text,
  p_campaign_code text default null,
  p_referral_code text default null,
  p_metadata jsonb default '{}'::jsonb
) returns bigint
language plpgsql security definer set search_path=public,private,auth,pg_temp as $$
declare v_id bigint;
begin
  perform private.crypto_assert_commercial_metadata_safe(coalesce(p_metadata,'{}'::jsonb));
  if p_user_id is not null and not exists(select 1 from auth.users u where u.id=p_user_id) then raise exception 'Auth user not found'; end if;
  if p_user_id is null and coalesce(p_session_hash,'') !~ '^[0-9a-f]{64}$' then raise exception 'Hashed anonymous session required'; end if;
  insert into public.crypto_commercial_funnel_events(user_id,anonymous_session_hash,event_type,source,campaign_code,referral_code,metadata)
  values(p_user_id,nullif(lower(p_session_hash),''),p_event_type,left(coalesce(nullif(btrim(p_source),''),'unknown'),80),nullif(p_campaign_code,''),nullif(p_referral_code,''),coalesce(p_metadata,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function private.service_attribute_crypto_referral(p_user_id uuid,p_referral_code text,p_source text default 'registration',p_evidence jsonb default '{}'::jsonb)
returns jsonb
language plpgsql security definer set search_path=public,private,auth,pg_temp as $$
declare v_config public.crypto_referral_program_config%rowtype;v_code public.crypto_referral_codes%rowtype;
begin
  perform private.crypto_assert_commercial_metadata_safe(coalesce(p_evidence,'{}'::jsonb));
  if p_user_id is null or not exists(select 1 from auth.users u where u.id=p_user_id) then raise exception 'Auth user required'; end if;
  select * into v_config from public.crypto_referral_program_config where singleton=true;
  if not coalesce(v_config.enabled,false) or not coalesce(v_config.activation_authorized,false) then raise exception 'REFERRAL_PROGRAM_DISABLED' using errcode='42501'; end if;
  select * into v_code from public.crypto_referral_codes where code=p_referral_code and status='active';
  if not found then raise exception 'REFERRAL_CODE_INACTIVE'; end if;
  insert into public.crypto_referral_attributions(user_id,referral_code,source,evidence)
  values(p_user_id,p_referral_code,p_source,coalesce(p_evidence,'{}'::jsonb))
  on conflict(user_id) do nothing;
  return jsonb_build_object('ok',true,'user_id',p_user_id,'referral_code',p_referral_code,'payout_created',false);
end;
$$;

create or replace function private.crypto_commercial_funnel_snapshot(p_days integer default 30)
returns jsonb
language sql security definer set search_path=public,pg_temp as $$
  with counts as (
    select event_type,count(*)::bigint as n
    from public.crypto_commercial_funnel_events
    where occurred_at >= now() - make_interval(days=>greatest(1,least(coalesce(p_days,30),365)))
    group by event_type
  )
  select jsonb_build_object(
    'window_days',greatest(1,least(coalesce(p_days,30),365)),
    'events',coalesce((select jsonb_object_agg(event_type,n) from counts),'{}'::jsonb),
    'total_events',(select count(*) from public.crypto_commercial_funnel_events where occurred_at >= now()-make_interval(days=>greatest(1,least(coalesce(p_days,30),365)))),
    'referral_program',(select jsonb_build_object('enabled',enabled,'activation_authorized',activation_authorized,'reward_model',reward_model,'attribution_window_days',attribution_window_days) from public.crypto_referral_program_config where singleton=true),
    'attributions',(select count(*) from public.crypto_referral_attributions)
  );
$$;

revoke all on function private.crypto_assert_commercial_metadata_safe(jsonb) from public,anon,authenticated;
revoke all on function private.service_record_crypto_funnel_event(uuid,text,text,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function private.service_attribute_crypto_referral(uuid,text,text,jsonb) from public,anon,authenticated;
revoke all on function private.crypto_commercial_funnel_snapshot(integer) from public,anon,authenticated;
grant execute on function private.service_record_crypto_funnel_event(uuid,text,text,text,text,text,jsonb) to service_role;
grant execute on function private.service_attribute_crypto_referral(uuid,text,text,jsonb) to service_role;
grant execute on function private.crypto_commercial_funnel_snapshot(integer) to service_role;

comment on table public.crypto_commercial_funnel_events is 'Prelaunch service-only commercial funnel evidence. No raw email/IP/secrets; activation-independent.';
comment on table public.crypto_referral_program_config is 'Referral program is prepared disabled. Commission/reward economics and activation require separate owner decision.';
comment on function private.service_attribute_crypto_referral(uuid,text,text,jsonb) is 'Fail-closed referral attribution; impossible while referral program is disabled. Never creates payouts.';
