create table if not exists public.crypto_operational_observations(
  id bigint generated by default as identity primary key,
  source_type text not null check(source_type in('edge','cron')),
  source_name text not null,
  observation_id text not null,
  observed_at timestamptz not null,
  success boolean not null,
  duration_ms bigint check(duration_ms is null or duration_ms>=0),
  status_code integer,
  created_at timestamptz not null default now(),
  unique(source_type,source_name,observation_id)
);

create index if not exists crypto_operational_observations_source_time_idx
on public.crypto_operational_observations(source_type,source_name,observed_at desc);
create index if not exists crypto_operational_observations_failures_idx
on public.crypto_operational_observations(observed_at desc)
where success=false;

alter table public.crypto_operational_observations enable row level security;
revoke all on table public.crypto_operational_observations from public,anon,authenticated;
grant select,insert,update,delete on table public.crypto_operational_observations to service_role;
grant usage,select on sequence public.crypto_operational_observations_id_seq to service_role;
drop policy if exists crypto_operational_observations_service_all on public.crypto_operational_observations;
create policy crypto_operational_observations_service_all
on public.crypto_operational_observations
for all to service_role
using(true) with check(true);

insert into public.crypto_operational_observations(
  source_type,source_name,observation_id,observed_at,success,duration_ms,status_code
)
select
  'edge',q.source_name,q.request_id::text,q.requested_at,
  not(
    r.id is null or coalesce(r.timed_out,false) or r.error_msg is not null
    or r.status_code<200 or r.status_code>=300
    or coalesce(r.content,'') like '%"success":false%'
  ),
  case when r.created is null then null else greatest(0,floor(extract(epoch from(r.created-q.requested_at))*1000)::bigint) end,
  r.status_code
from public.crypto_operational_http_requests q
left join net._http_response r on r.id=q.request_id
where q.requested_at>=now()-interval '90 days'
on conflict(source_type,source_name,observation_id) do nothing;

insert into public.crypto_operational_observations(
  source_type,source_name,observation_id,observed_at,success,duration_ms,status_code
)
select
  'cron',j.jobname,d.runid::text,d.start_time,d.status='succeeded',
  case when d.end_time is null then null else greatest(0,floor(extract(epoch from(d.end_time-d.start_time))*1000)::bigint) end,
  null
from cron.job j
join cron.job_run_details d on d.jobid=j.jobid
where d.status in('succeeded','failed') and d.start_time is not null
  and d.start_time>=now()-interval '90 days'
  and j.jobname in(
    'crypto-signal-monitor-every-minute','crypto-market-scanner-every-15-minutes',
    'crypto-lab-daily-maintenance','crypto-lab-subscription-lifecycle',
    'crypto-lab-billing-event-retry','crypto-lab-billing-reconciliation',
    'crypto-lab-incident-reconciliation'
  )
on conflict(source_type,source_name,observation_id) do nothing;

create or replace function private.reconcile_crypto_operational_incidents()
returns jsonb
language plpgsql
security definer
set search_path to 'public','private','cron','net','pg_temp'
as $$
declare
  v_edge record;
  v_cron record;
  v_failed boolean;
  v_fingerprint text;
  v_observation text;
  v_opened integer:=0;
  v_resolved integer:=0;
  v_http_processed integer:=0;
  v_cron_processed integer:=0;
begin
  for v_edge in
    select q.request_id,q.source_name,q.requested_at,r.status_code,r.timed_out,r.error_msg,r.content,r.created as response_created
    from public.crypto_operational_http_requests q
    left join net._http_response r on r.id=q.request_id
    where q.processed_at is null
      and (r.id is not null or q.requested_at<now()-interval '2 minutes')
    order by q.requested_at
    limit 500
  loop
    v_fingerprint:='edge:'||v_edge.source_name;
    v_observation:=v_edge.request_id::text;
    v_failed:=v_edge.status_code is null
      or coalesce(v_edge.timed_out,false)
      or v_edge.error_msg is not null
      or v_edge.status_code<200
      or v_edge.status_code>=300
      or coalesce(v_edge.content,'') like '%"success":false%';

    insert into public.crypto_operational_observations(
      source_type,source_name,observation_id,observed_at,success,duration_ms,status_code
    ) values (
      'edge',v_edge.source_name,v_observation,v_edge.requested_at,not v_failed,
      case when v_edge.response_created is null then null else greatest(0,floor(extract(epoch from(v_edge.response_created-v_edge.requested_at))*1000)::bigint) end,
      v_edge.status_code
    ) on conflict(source_type,source_name,observation_id) do nothing;

    if v_failed then
      insert into public.crypto_operational_incidents(
        fingerprint,source_type,source_name,status,severity,first_seen_at,last_seen_at,occurrences,
        last_observation_id,last_status_code,last_error,resolved_at,resolution_note
      ) values (
        v_fingerprint,'edge',v_edge.source_name,'open','high',v_edge.requested_at,now(),1,
        v_observation,v_edge.status_code,
        case
          when v_edge.status_code is null then 'No HTTP response within two minutes'
          when coalesce(v_edge.timed_out,false) then 'HTTP request timed out'
          when v_edge.error_msg is not null then 'HTTP transport error'
          when v_edge.status_code<200 or v_edge.status_code>=300 then 'HTTP status '||v_edge.status_code::text
          else 'Edge Function returned success=false'
        end,
        null,null
      )
      on conflict(fingerprint) do update set
        status='open',severity='high',
        first_seen_at=case when public.crypto_operational_incidents.status='resolved' then excluded.first_seen_at else public.crypto_operational_incidents.first_seen_at end,
        last_seen_at=excluded.last_seen_at,
        occurrences=case when public.crypto_operational_incidents.status='resolved' then 1 else public.crypto_operational_incidents.occurrences+1 end,
        last_observation_id=excluded.last_observation_id,
        last_status_code=excluded.last_status_code,last_error=excluded.last_error,
        resolved_at=null,resolution_note=null,updated_at=now()
      where public.crypto_operational_incidents.last_observation_id is distinct from excluded.last_observation_id;
      if found then v_opened:=v_opened+1; end if;
    else
      update public.crypto_operational_incidents
      set status='resolved',resolved_at=now(),resolution_note='Recovered on successful Edge response',
          last_observation_id=v_observation,last_status_code=v_edge.status_code,last_error=null,last_seen_at=now(),updated_at=now()
      where fingerprint=v_fingerprint and status='open' and last_observation_id is distinct from v_observation;
      if found then v_resolved:=v_resolved+1; end if;
    end if;

    update public.crypto_operational_http_requests set processed_at=now() where request_id=v_edge.request_id;
    v_http_processed:=v_http_processed+1;
  end loop;

  for v_cron in
    select j.jobname,d.runid,d.status,d.start_time,d.end_time,left(coalesce(d.return_message,''),160) as return_message
    from cron.job j
    join public.crypto_operational_cursors c on c.source_type='cron' and c.source_name=j.jobname
    join cron.job_run_details d on d.jobid=j.jobid
      and d.runid>c.last_observation_id
      and d.status in('succeeded','failed')
      and d.start_time is not null
    where j.jobname in(
      'crypto-signal-monitor-every-minute','crypto-market-scanner-every-15-minutes',
      'crypto-lab-daily-maintenance','crypto-lab-subscription-lifecycle',
      'crypto-lab-billing-event-retry','crypto-lab-billing-reconciliation',
      'crypto-lab-incident-reconciliation'
    )
    order by d.runid
    limit 2000
  loop
    v_fingerprint:='cron:'||v_cron.jobname;
    v_observation:=v_cron.runid::text;

    insert into public.crypto_operational_observations(
      source_type,source_name,observation_id,observed_at,success,duration_ms,status_code
    ) values (
      'cron',v_cron.jobname,v_observation,v_cron.start_time,v_cron.status='succeeded',
      case when v_cron.end_time is null then null else greatest(0,floor(extract(epoch from(v_cron.end_time-v_cron.start_time))*1000)::bigint) end,
      null
    ) on conflict(source_type,source_name,observation_id) do nothing;

    if v_cron.status='failed' then
      insert into public.crypto_operational_incidents(
        fingerprint,source_type,source_name,status,severity,first_seen_at,last_seen_at,occurrences,
        last_observation_id,last_error,resolved_at,resolution_note
      ) values (
        v_fingerprint,'cron',v_cron.jobname,'open','high',v_cron.start_time,now(),1,
        v_observation,left('Cron failed: '||coalesce(nullif(v_cron.return_message,''),'no bounded message'),200),null,null
      )
      on conflict(fingerprint) do update set
        status='open',severity='high',
        first_seen_at=case when public.crypto_operational_incidents.status='resolved' then excluded.first_seen_at else public.crypto_operational_incidents.first_seen_at end,
        last_seen_at=excluded.last_seen_at,
        occurrences=case when public.crypto_operational_incidents.status='resolved' then 1 else public.crypto_operational_incidents.occurrences+1 end,
        last_observation_id=excluded.last_observation_id,last_error=excluded.last_error,
        resolved_at=null,resolution_note=null,updated_at=now()
      where public.crypto_operational_incidents.last_observation_id is distinct from excluded.last_observation_id;
      if found then v_opened:=v_opened+1; end if;
    else
      update public.crypto_operational_incidents
      set status='resolved',resolved_at=now(),resolution_note='Recovered on successful cron execution',
          last_observation_id=v_observation,last_error=null,last_seen_at=now(),updated_at=now()
      where fingerprint=v_fingerprint and status='open' and last_observation_id is distinct from v_observation;
      if found then v_resolved:=v_resolved+1; end if;
    end if;

    insert into public.crypto_operational_cursors(source_type,source_name,last_observation_id,updated_at)
    values('cron',v_cron.jobname,v_cron.runid,now())
    on conflict(source_type,source_name) do update set
      last_observation_id=greatest(public.crypto_operational_cursors.last_observation_id,excluded.last_observation_id),
      updated_at=now();
    v_cron_processed:=v_cron_processed+1;
  end loop;

  delete from public.crypto_operational_http_requests where processed_at<now()-interval '30 days';
  delete from public.crypto_operational_observations where observed_at<now()-interval '90 days';
  delete from public.crypto_operational_incidents where status='resolved' and resolved_at<now()-interval '180 days';

  return jsonb_build_object(
    'success',true,
    'http_requests_processed',v_http_processed,
    'cron_runs_processed',v_cron_processed,
    'incidents_opened_or_updated',v_opened,
    'incidents_resolved',v_resolved,
    'open_incidents',(select count(*) from public.crypto_operational_incidents where status='open'),
    'resolved_incidents',(select count(*) from public.crypto_operational_incidents where status='resolved'),
    'observations_24h',(select count(*) from public.crypto_operational_observations where observed_at>=now()-interval '24 hours')
  );
end;
$$;

create or replace function private.get_crypto_admin_operational_slo()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','private','cron','pg_temp'
as $$
declare
  v_sources jsonb;
  v_cursor_lag jsonb;
  v_result jsonb;
begin
  if not public.crypto_is_admin() then
    raise exception 'Admin access required' using errcode='42501';
  end if;

  with cfg(source_type,source_name,min_success_pct,max_p95_ms,max_age_minutes,min_samples_24h) as (
    values
      ('edge'::text,'crypto-signal-monitor'::text,99.0::numeric,5000::bigint,3::numeric,30::bigint),
      ('edge','crypto-market-scanner',95.0,120000,30,3),
      ('cron','crypto-lab-incident-reconciliation',95.0,30000,15,6)
  ), metrics as (
    select c.*,
      (select count(*) from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '24 hours') as samples_24h,
      (select count(*) from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '1 hour') as samples_1h,
      (select count(*) from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '1 hour' and not o.success) as failures_1h,
      (select round(100.0*avg(case when o.success then 1 else 0 end),2) from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '24 hours') as success_pct_24h,
      (select round(100.0*avg(case when o.success then 1 else 0 end),2) from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '1 hour') as success_pct_1h,
      (select round(percentile_cont(0.95) within group(order by o.duration_ms))::bigint from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '24 hours' and o.duration_ms is not null) as p95_ms_24h,
      (select round(avg(o.duration_ms))::bigint from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '24 hours' and o.duration_ms is not null) as avg_ms_24h,
      (select max(o.duration_ms) from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name and o.observed_at>=now()-interval '24 hours') as max_ms_24h,
      (select max(o.observed_at) from public.crypto_operational_observations o where o.source_type=c.source_type and o.source_name=c.source_name) as last_observed_at
    from cfg c
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'source_type',source_type,'source_name',source_name,
    'samples_24h',samples_24h,'samples_1h',samples_1h,'failures_1h',failures_1h,
    'success_pct_24h',success_pct_24h,'success_pct_1h',success_pct_1h,
    'p95_ms_24h',p95_ms_24h,'avg_ms_24h',avg_ms_24h,'max_ms_24h',max_ms_24h,
    'last_observed_at',last_observed_at,
    'age_minutes',case when last_observed_at is null then null else round(extract(epoch from(now()-last_observed_at))/60.0,1) end,
    'thresholds',jsonb_build_object('min_success_pct',min_success_pct,'max_p95_ms',max_p95_ms,'max_age_minutes',max_age_minutes,'min_samples_24h',min_samples_24h),
    'state',case
      when last_observed_at is null or extract(epoch from(now()-last_observed_at))/60.0>max_age_minutes then 'warning'
      when failures_1h>0 then 'warning'
      when samples_24h>=min_samples_24h and coalesce(success_pct_24h,0)<min_success_pct then 'warning'
      when samples_24h>=min_samples_24h and coalesce(p95_ms_24h,0)>max_p95_ms then 'warning'
      when samples_24h<min_samples_24h then 'collecting'
      else 'healthy'
    end
  ) order by source_type,source_name),'[]'::jsonb) into v_sources
  from metrics;

  select coalesce(jsonb_agg(jsonb_build_object(
    'source_name',j.jobname,
    'cursor_runid',coalesce(c.last_observation_id,0),
    'latest_terminal_runid',coalesce(x.latest_runid,0),
    'pending_terminal_runs',coalesce(x.pending_count,0),
    'oldest_pending_minutes',case when x.oldest_start is null then null else round(extract(epoch from(now()-x.oldest_start))/60.0,1) end,
    'warning',coalesce(x.pending_count,0)>2 or (x.oldest_start is not null and now()-x.oldest_start>interval '15 minutes')
  ) order by j.jobname),'[]'::jsonb) into v_cursor_lag
  from cron.job j
  left join public.crypto_operational_cursors c on c.source_type='cron' and c.source_name=j.jobname
  left join lateral(
    select max(d.runid) as latest_runid,count(*) filter(where d.runid>coalesce(c.last_observation_id,0)) as pending_count,
           min(d.start_time) filter(where d.runid>coalesce(c.last_observation_id,0)) as oldest_start
    from cron.job_run_details d
    where d.jobid=j.jobid and d.status in('succeeded','failed') and d.start_time is not null
  ) x on true
  where j.jobname in(
    'crypto-signal-monitor-every-minute','crypto-market-scanner-every-15-minutes',
    'crypto-lab-daily-maintenance','crypto-lab-subscription-lifecycle',
    'crypto-lab-billing-event-retry','crypto-lab-billing-reconciliation',
    'crypto-lab-incident-reconciliation'
  );

  select jsonb_build_object(
    'generated_at',now(),
    'sources',v_sources,
    'backpressure',jsonb_build_object(
      'outbox',jsonb_build_object(
        'total',(select count(*) from public.crypto_signal_notification_outbox),
        'unsent',(select count(*) from public.crypto_signal_notification_outbox where status in('pending','processing','retry','dead')),
        'oldest_unsent_minutes',(select round(extract(epoch from(now()-min(created_at)))/60.0,1) from public.crypto_signal_notification_outbox where status in('pending','processing','retry','dead')),
        'warning',(select count(*)>=100 from public.crypto_signal_notification_outbox where status in('pending','processing','retry','dead'))
          or coalesce((select now()-min(created_at)>interval '5 minutes' from public.crypto_signal_notification_outbox where status in('pending','processing','retry','dead')),false)
      ),
      'operational_requests',jsonb_build_object(
        'total',(select count(*) from public.crypto_operational_http_requests),
        'pending',(select count(*) from public.crypto_operational_http_requests where processed_at is null),
        'oldest_pending_minutes',(select round(extract(epoch from(now()-min(requested_at)))/60.0,1) from public.crypto_operational_http_requests where processed_at is null),
        'warning',(select count(*)>=100 from public.crypto_operational_http_requests where processed_at is null)
          or coalesce((select now()-min(requested_at)>interval '10 minutes' from public.crypto_operational_http_requests where processed_at is null),false)
      ),
      'monitor_capacity',jsonb_build_object(
        'live_signals',(select count(*) from public.crypto_signal_monitors where status in('WAITING','ACTIVE')),
        'hard_limit',10000,
        'usage_pct',round(100.0*(select count(*) from public.crypto_signal_monitors where status in('WAITING','ACTIVE'))/10000.0,2),
        'warning',(select count(*)>=8000 from public.crypto_signal_monitors where status in('WAITING','ACTIVE'))
      ),
      'cursor_lag',v_cursor_lag
    ),
    'retention',jsonb_build_object(
      'processed_http_days',30,'observations_days',90,'resolved_incidents_days',180,
      'outbox_sent_dead_days',180,'open_incidents_deleted',false,'active_cursors_deleted',false
    )
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.get_crypto_admin_operational_slo()
returns jsonb
language sql
stable
security invoker
set search_path to 'public','private','pg_temp'
as $$ select private.get_crypto_admin_operational_slo() $$;

revoke all on function private.get_crypto_admin_operational_slo() from public,anon;
revoke all on function public.get_crypto_admin_operational_slo() from public,anon;
grant execute on function private.get_crypto_admin_operational_slo() to authenticated,service_role;
grant execute on function public.get_crypto_admin_operational_slo() to authenticated,service_role;

alter table public.crypto_maintenance_runs
  add column if not exists operational_requests_deleted integer not null default 0,
  add column if not exists operational_observations_deleted integer not null default 0,
  add column if not exists resolved_incidents_deleted integer not null default 0;

create or replace function public.run_crypto_maintenance()
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $$
declare
  v_run_id bigint; v_ai integer:=0; v_backtests integer:=0; v_leases integer:=0;
  v_registration integer:=0; v_recovery integer:=0; v_rate_events integer:=0;
  v_scanner integer:=0; v_old_runs integer:=0; v_outbox integer:=0;
  v_operational_requests integer:=0; v_observations integer:=0; v_resolved_incidents integer:=0; v_error text;
begin
  insert into public.crypto_maintenance_runs(status) values('started') returning id into v_run_id;
  begin
    update public.crypto_ai_runs set status='failed',completed_at=coalesce(completed_at,now()),duration_ms=coalesce(duration_ms,greatest(0,floor(extract(epoch from(now()-created_at))*1000)::integer)),error_code=coalesce(error_code,'STALE_RUN'),error_message=coalesce(error_message,'AI run exceeded 15 minutes without completion') where status='started' and created_at<now()-interval '15 minutes'; get diagnostics v_ai=row_count;
    update public.crypto_backtest_runs set status='failed',completed_at=coalesce(completed_at,now()),duration_ms=coalesce(duration_ms,greatest(0,floor(extract(epoch from(now()-created_at))*1000)::integer)),error_code=coalesce(error_code,'STALE_RUN'),error_message=coalesce(error_message,'Backtest run exceeded 30 minutes without completion') where status='started' and created_at<now()-interval '30 minutes'; get diagnostics v_backtests=row_count;
    delete from public.crypto_feature_access_leases where expires_at<now()-interval '1 day'; get diagnostics v_leases=row_count;
    delete from public.crypto_registration_attempts where created_at<now()-interval '30 days'; get diagnostics v_registration=row_count;
    delete from public.crypto_recovery_attempts where created_at<now()-interval '30 days'; get diagnostics v_recovery=row_count;
    delete from public.crypto_feature_rate_events where created_at<now()-interval '2 days'; get diagnostics v_rate_events=row_count;
    delete from public.crypto_scanner_runs where started_at<now()-interval '180 days'; get diagnostics v_scanner=row_count;
    delete from public.crypto_signal_notification_outbox where status in('sent','dead') and created_at<now()-interval '180 days'; get diagnostics v_outbox=row_count;
    delete from public.crypto_operational_http_requests where processed_at is not null and processed_at<now()-interval '30 days'; get diagnostics v_operational_requests=row_count;
    delete from public.crypto_operational_observations where observed_at<now()-interval '90 days'; get diagnostics v_observations=row_count;
    delete from public.crypto_operational_incidents where status='resolved' and resolved_at<now()-interval '180 days'; get diagnostics v_resolved_incidents=row_count;
    delete from public.crypto_maintenance_runs where started_at<now()-interval '180 days' and id<>v_run_id; get diagnostics v_old_runs=row_count;
    update public.crypto_maintenance_runs set completed_at=now(),status='completed',stale_ai_marked=v_ai,stale_backtests_marked=v_backtests,expired_leases_deleted=v_leases,registration_attempts_deleted=v_registration,recovery_attempts_deleted=v_recovery,rate_events_deleted=v_rate_events,scanner_runs_deleted=v_scanner,notification_outbox_deleted=v_outbox,operational_requests_deleted=v_operational_requests,operational_observations_deleted=v_observations,resolved_incidents_deleted=v_resolved_incidents,old_maintenance_rows_deleted=v_old_runs where id=v_run_id;
    return jsonb_build_object('success',true,'run_id',v_run_id,'stale_ai_marked',v_ai,'stale_backtests_marked',v_backtests,'expired_leases_deleted',v_leases,'registration_attempts_deleted',v_registration,'recovery_attempts_deleted',v_recovery,'rate_events_deleted',v_rate_events,'scanner_runs_deleted',v_scanner,'notification_outbox_deleted',v_outbox,'operational_requests_deleted',v_operational_requests,'operational_observations_deleted',v_observations,'resolved_incidents_deleted',v_resolved_incidents,'old_maintenance_rows_deleted',v_old_runs);
  exception when others then
    get stacked diagnostics v_error=message_text;
    update public.crypto_maintenance_runs set completed_at=now(),status='failed',error_message=left(v_error,2000) where id=v_run_id;
    return jsonb_build_object('success',false,'run_id',v_run_id,'error',left(v_error,500));
  end;
end;
$$;

revoke all on function private.reconcile_crypto_operational_incidents() from public,anon,authenticated;
grant execute on function private.reconcile_crypto_operational_incidents() to service_role;
notify pgrst,'reload schema';