-- CRYPTO LAB v79 — SMART MONEY / derivatives snapshot core
-- Production migration applied 2026-08-18.

create table if not exists public.crypto_smart_money_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  symbol text not null,
  timeframe text not null,
  source text not null default 'binance_usdsm',
  mark_price numeric,
  price_change_pct numeric,
  whale_threshold_usd numeric,
  whale_buy_usd numeric,
  whale_sell_usd numeric,
  whale_delta_usd numeric,
  whale_pressure numeric,
  cvd_usd numeric,
  cvd_pressure numeric,
  taker_buy_sell_ratio numeric,
  open_interest_usd numeric,
  open_interest_change_pct numeric,
  funding_rate numeric,
  orderbook_imbalance numeric,
  top_position_ratio numeric,
  top_account_ratio numeric,
  smart_score integer,
  smart_direction text,
  data_quality text not null default 'partial',
  metadata jsonb not null default '{}'::jsonb,
  constraint crypto_smart_money_symbol_chk check (symbol ~ '^[A-Z0-9]{2,20}$'),
  constraint crypto_smart_money_tf_chk check (timeframe in ('5M','15M','1H','4H','1D','1W','1MO')),
  constraint crypto_smart_money_direction_chk check (smart_direction is null or smart_direction in ('BUY','SELL','NEUTRAL')),
  constraint crypto_smart_money_score_chk check (smart_score is null or smart_score between 0 and 100)
);

create index if not exists crypto_smart_money_symbol_tf_time_idx
  on public.crypto_smart_money_snapshots(symbol,timeframe,captured_at desc);
create index if not exists crypto_smart_money_time_idx
  on public.crypto_smart_money_snapshots(captured_at desc);

alter table public.crypto_smart_money_snapshots enable row level security;
revoke all on public.crypto_smart_money_snapshots from anon, authenticated;
grant select,insert,update,delete on public.crypto_smart_money_snapshots to service_role;
grant usage,select on sequence public.crypto_smart_money_snapshots_id_seq to service_role;

create or replace function private.cleanup_crypto_smart_money_snapshots(p_keep interval default interval '45 days')
returns bigint
language plpgsql
security definer
set search_path=public,private,pg_temp
as $function$
declare v_count bigint;
begin
  delete from public.crypto_smart_money_snapshots where captured_at < now()-p_keep;
  get diagnostics v_count = row_count;
  return v_count;
end
$function$;

revoke all on function private.cleanup_crypto_smart_money_snapshots(interval) from public,anon,authenticated;
grant execute on function private.cleanup_crypto_smart_money_snapshots(interval) to service_role;
