-- CRYPTO LAB v79 — archive Scanner market universe/rank every 15 minutes.
-- This closes the historical parity gap for future Scanner v15 backtests.
create table if not exists public.crypto_scanner_market_snapshots(
 id bigint generated by default as identity primary key,
 batch_id uuid not null,
 captured_at timestamptz not null,
 symbol text not null,
 liquidity_rank integer not null,
 quote_volume numeric not null,
 range_pct numeric,
 change_pct numeric,
 eligible boolean not null default true,
 created_at timestamptz not null default now(),
 unique(batch_id,symbol)
);
create index if not exists crypto_scanner_market_snapshot_time_idx on public.crypto_scanner_market_snapshots(captured_at desc,symbol);
alter table public.crypto_scanner_market_snapshots enable row level security;
revoke all on public.crypto_scanner_market_snapshots from public,anon,authenticated;
grant select,insert,update,delete on public.crypto_scanner_market_snapshots to service_role;

-- Operational source support for crypto-market-snapshot was applied to
-- crypto_operational_http_requests, track_crypto_operational_http_request and
-- dispatch_crypto_operational_edge in production. Production cron:
-- crypto-market-snapshot-every-15-minutes => */15 * * * *
