create table if not exists public.crypto_maintenance_evidence_seals(
  id bigint generated by default as identity primary key,
  maintenance_run_id bigint not null unique references public.crypto_maintenance_runs(id) on delete restrict,
  manifest_id bigint not null references public.crypto_release_manifests(id) on delete restrict,
  release_checkpoint_id bigint references public.crypto_release_checkpoints(id) on delete set null,
  evidence_version integer not null default 1 check(evidence_version=1),
  expected_after timestamptz not null,
  run_started_at timestamptz not null,
  run_completed_at timestamptz,
  run_status text not null,
  counters jsonb not null default '{}'::jsonb,
  integrity_state text not null check(integrity_state in('healthy','warning','critical','collecting')),
  drift_state text not null check(drift_state in('healthy','warning','critical','collecting')),
  seal_status text not null check(seal_status in('passed','failed')),
  failure_codes jsonb not null default '[]'::jsonb check(jsonb_typeof(failure_codes)='array'),
  evidence_hash text not null unique check(evidence_hash ~ '^[0-9a-f]{64}$'),
  sealed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists crypto_maintenance_evidence_seals_manifest_idx
  on public.crypto_maintenance_evidence_seals(manifest_id,sealed_at desc);
create index if not exists crypto_maintenance_evidence_seals_checkpoint_idx
  on public.crypto_maintenance_evidence_seals(release_checkpoint_id)
  where release_checkpoint_id is not null;

alter table public.crypto_maintenance_evidence_seals enable row level security;
revoke all on public.crypto_maintenance_evidence_seals from public,anon,authenticated;
grant select,insert,update,delete on public.crypto_maintenance_evidence_seals to service_role;

drop policy if exists crypto_maintenance_evidence_seals_browser_deny on public.crypto_maintenance_evidence_seals;
create policy crypto_maintenance_evidence_seals_browser_deny
  on public.crypto_maintenance_evidence_seals
  for all to anon,authenticated
  using(false) with check(false);

create or replace function private.crypto_maintenance_counter_snapshot(p_run_id bigint)
returns jsonb
language sql
stable
security definer
set search_path to 'public','pg_catalog','pg_temp'
as $$
  select jsonb_build_object(
    'stale_ai_marked',stale_ai_marked,
    'stale_backtests_marked',stale_backtests_marked,
    'expired_leases_deleted',expired_leases_deleted,
    'registration_attempts_deleted',registration_attempts_deleted,
    'recovery_attempts_deleted',recovery_attempts_deleted,
    'rate_events_deleted',rate_events_deleted,
    'scanner_runs_deleted',scanner_runs_deleted,
    'notification_outbox_deleted',notification_outbox_deleted,
    'operational_requests_deleted',operational_requests_deleted,
    'operational_observations_deleted',operational_observations_deleted,
    'resolved_incidents_deleted',resolved_incidents_deleted,
    'operational_incidents_deleted',operational_incidents_deleted,
    'operational_cursors_deleted',operational_cursors_deleted,
    'old_maintenance_rows_deleted',old_maintenance_rows_deleted
  )
  from public.crypto_maintenance_runs where id=p_run_id
$$;
revoke all on function private.crypto_maintenance_counter_snapshot(bigint) from public,anon,authenticated;
grant execute on function private.crypto_maintenance_counter_snapshot(bigint) to service_role;

create or replace function private.service_seal_latest_crypto_maintenance(
  p_manifest_key text default null,
  p_min_started_at timestamptz default timestamptz '2026-08-05 03:17:00+00'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','private','pg_catalog','pg_temp'
as $$
declare
  v_manifest public.crypto_release_manifests%rowtype;
  v_run public.crypto_maintenance_runs%rowtype;
  v_checkpoint_id bigint;
  v_integrity jsonb;
  v_drift jsonb;
  v_counters jsonb;
  v_failures jsonb:='[]'::jsonb;
  v_status text;
  v_payload jsonb;
  v_hash text;
  v_seal_id bigint;
  v_existing public.crypto_maintenance_evidence_seals%rowtype;
begin
  select * into v_manifest
  from public.crypto_release_manifests
  where active and (p_manifest_key is null or manifest_key=p_manifest_key)
  order by created_at desc,id desc limit 1;
  if v_manifest.id is null then
    raise exception 'Active release manifest not found' using errcode='P0002';
  end if;

  select * into v_run
  from public.crypto_maintenance_runs
  where started_at>=p_min_started_at
  order by started_at desc,id desc limit 1;
  if v_run.id is null then
    return jsonb_build_object(
      'sealed',false,'status','pending','reason','maintenance_run_not_available',
      'manifest_key',v_manifest.manifest_key,'expected_after',p_min_started_at
    );
  end if;

  select * into v_existing from public.crypto_maintenance_evidence_seals where maintenance_run_id=v_run.id;
  if v_existing.id is not null then
    return jsonb_build_object(
      'sealed',true,'id',v_existing.id,'status',v_existing.seal_status,
      'maintenance_run_id',v_existing.maintenance_run_id,'evidence_hash',v_existing.evidence_hash,
      'sealed_at',v_existing.sealed_at,'idempotent',true
    );
  end if;

  select id into v_checkpoint_id
  from public.crypto_release_checkpoints
  where build=v_manifest.build
  order by id desc limit 1;

  v_integrity:=private.crypto_data_integrity_snapshot();
  v_drift:=private.crypto_release_drift_snapshot();
  v_counters:=private.crypto_maintenance_counter_snapshot(v_run.id);

  if v_run.status<>'completed' then v_failures:=v_failures||jsonb_build_array('maintenance_not_completed'); end if;
  if v_run.completed_at is null then v_failures:=v_failures||jsonb_build_array('maintenance_completion_time_missing'); end if;
  if v_run.error_message is not null then v_failures:=v_failures||jsonb_build_array('maintenance_error_present'); end if;
  if coalesce(v_integrity->>'state','critical')<>'healthy' then v_failures:=v_failures||jsonb_build_array('data_integrity_not_healthy'); end if;
  if coalesce(v_drift->>'state','critical')<>'healthy' then v_failures:=v_failures||jsonb_build_array('release_drift_not_healthy'); end if;
  if exists(
    select 1 from jsonb_each_text(v_counters) e
    where e.value !~ '^[0-9]+$' or e.value::numeric<0
  ) then v_failures:=v_failures||jsonb_build_array('invalid_retention_counter'); end if;

  v_status:=case when jsonb_array_length(v_failures)=0 then 'passed' else 'failed' end;
  v_payload:=jsonb_build_object(
    'evidence_version',1,
    'manifest_key',v_manifest.manifest_key,
    'manifest_source_commit',v_manifest.source_commit,
    'maintenance_run_id',v_run.id,
    'expected_after',p_min_started_at,
    'run_started_at',v_run.started_at,
    'run_completed_at',v_run.completed_at,
    'run_status',v_run.status,
    'counters',v_counters,
    'integrity_state',coalesce(v_integrity->>'state','critical'),
    'drift_state',coalesce(v_drift->>'state','critical'),
    'seal_status',v_status,
    'failure_codes',v_failures
  );
  v_hash:=encode(digest(convert_to(v_payload::text,'UTF8'),'sha256'),'hex');

  insert into public.crypto_maintenance_evidence_seals(
    maintenance_run_id,manifest_id,release_checkpoint_id,evidence_version,expected_after,
    run_started_at,run_completed_at,run_status,counters,integrity_state,drift_state,
    seal_status,failure_codes,evidence_hash
  ) values(
    v_run.id,v_manifest.id,v_checkpoint_id,1,p_min_started_at,
    v_run.started_at,v_run.completed_at,v_run.status,v_counters,
    coalesce(v_integrity->>'state','critical'),coalesce(v_drift->>'state','critical'),
    v_status,v_failures,v_hash
  ) returning id into v_seal_id;

  if v_checkpoint_id is not null then
    update public.crypto_release_checkpoints
    set evidence=coalesce(evidence,'{}'::jsonb)||jsonb_build_object(
      'maintenance_evidence',jsonb_build_object(
        'seal_id',v_seal_id,'maintenance_run_id',v_run.id,'status',v_status,
        'evidence_hash',v_hash,'sealed_at',now(),'counters',v_counters
      )
    )
    where id=v_checkpoint_id;
  end if;

  return jsonb_build_object(
    'sealed',true,'id',v_seal_id,'status',v_status,'maintenance_run_id',v_run.id,
    'evidence_hash',v_hash,'failure_codes',v_failures,'checkpoint_id',v_checkpoint_id,
    'counters',v_counters
  );
end;
$$;
revoke all on function private.service_seal_latest_crypto_maintenance(text,timestamptz) from public,anon,authenticated;
grant execute on function private.service_seal_latest_crypto_maintenance(text,timestamptz) to service_role;

create or replace function private.get_crypto_admin_maintenance_evidence()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','private','pg_catalog','pg_temp'
as $$
declare
  v_expected timestamptz:=timestamptz '2026-08-05 03:17:00+00';
  v_run public.crypto_maintenance_runs%rowtype;
  v_seal public.crypto_maintenance_evidence_seals%rowtype;
  v_state text;
begin
  if not public.crypto_is_admin() then
    raise exception 'Admin access required' using errcode='42501';
  end if;
  select * into v_run from public.crypto_maintenance_runs
  where started_at>=v_expected order by started_at desc,id desc limit 1;
  if v_run.id is not null then
    select * into v_seal from public.crypto_maintenance_evidence_seals
    where maintenance_run_id=v_run.id order by id desc limit 1;
  end if;
  v_state:=case
    when now()<v_expected then 'healthy'
    when v_run.id is null and now()<v_expected+interval '30 minutes' then 'collecting'
    when v_run.id is null and now()<v_expected+interval '2 hours' then 'warning'
    when v_run.id is null then 'critical'
    when v_run.status='failed' or v_run.error_message is not null then 'critical'
    when v_seal.id is null and now()<coalesce(v_run.completed_at,v_run.started_at)+interval '30 minutes' then 'collecting'
    when v_seal.id is null then 'warning'
    when v_seal.seal_status='failed' then 'critical'
    else 'healthy' end;
  return jsonb_build_object(
    'state',v_state,'expected_after',v_expected,'generated_at',now(),
    'maintenance_run',case when v_run.id is null then null else jsonb_build_object(
      'id',v_run.id,'started_at',v_run.started_at,'completed_at',v_run.completed_at,
      'status',v_run.status,'has_error',v_run.error_message is not null,
      'counters',private.crypto_maintenance_counter_snapshot(v_run.id)
    ) end,
    'seal',case when v_seal.id is null then null else jsonb_build_object(
      'id',v_seal.id,'status',v_seal.seal_status,'evidence_hash',v_seal.evidence_hash,
      'failure_codes',v_seal.failure_codes,'sealed_at',v_seal.sealed_at,
      'release_checkpoint_id',v_seal.release_checkpoint_id
    ) end
  );
end;
$$;

create or replace function public.get_crypto_admin_maintenance_evidence()
returns jsonb
language sql
stable
security invoker
set search_path to 'public','private','pg_temp'
as $$ select private.get_crypto_admin_maintenance_evidence() $$;
revoke all on function private.get_crypto_admin_maintenance_evidence() from public,anon;
revoke all on function public.get_crypto_admin_maintenance_evidence() from public,anon;
grant execute on function private.get_crypto_admin_maintenance_evidence() to authenticated,service_role;
grant execute on function public.get_crypto_admin_maintenance_evidence() to authenticated,service_role;

alter function private.get_crypto_admin_operational_summary() rename to get_crypto_admin_operational_summary_maintenance_base;
create or replace function private.get_crypto_admin_operational_summary()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','private','pg_temp'
as $$
declare
  v_base jsonb;
  v_evidence jsonb;
  v_indicator jsonb;
  v_state text;
  v_base_state text;
  v_counts jsonb;
  v_healthy integer;
  v_warning integer;
  v_critical integer;
  v_collecting integer;
begin
  if not public.crypto_is_admin() then
    raise exception 'Admin access required' using errcode='42501';
  end if;
  v_base:=private.get_crypto_admin_operational_summary_maintenance_base();
  v_evidence:=private.get_crypto_admin_maintenance_evidence();
  v_state:=coalesce(v_evidence->>'state','critical');
  v_base_state:=coalesce(v_base->>'overall_state','critical');
  v_indicator:=jsonb_build_object(
    'code','maintenance_evidence','state',v_state,'owner','operations',
    'action_code','maintenance_evidence_runbook',
    'metrics',jsonb_build_object(
      'expected_after',v_evidence->'expected_after',
      'run_id',v_evidence#>'{maintenance_run,id}',
      'run_status',v_evidence#>'{maintenance_run,status}',
      'seal_id',v_evidence#>'{seal,id}',
      'seal_status',v_evidence#>'{seal,status}',
      'generated_at',v_evidence->'generated_at'
    )
  );
  v_counts:=coalesce(v_base->'counts','{}'::jsonb);
  v_healthy:=coalesce((v_counts->>'healthy')::integer,0)+(case when v_state='healthy' then 1 else 0 end);
  v_warning:=coalesce((v_counts->>'warning')::integer,0)+(case when v_state='warning' then 1 else 0 end);
  v_critical:=coalesce((v_counts->>'critical')::integer,0)+(case when v_state='critical' then 1 else 0 end);
  v_collecting:=coalesce((v_counts->>'collecting')::integer,0)+(case when v_state='collecting' then 1 else 0 end);
  return v_base||jsonb_build_object(
    'overall_state',case when v_base_state='critical' or v_state='critical' then 'critical'
      when v_base_state='warning' or v_state='warning' then 'warning'
      when v_base_state='collecting' or v_state='collecting' then 'collecting' else 'healthy' end,
    'decision',case when v_base_state='critical' or v_state='critical' then 'NO_GO'
      when v_base_state in('warning','collecting') or v_state in('warning','collecting') then 'WATCH' else 'TECHNICAL_GO' end,
    'counts',jsonb_build_object('healthy',v_healthy,'warning',v_warning,'critical',v_critical,'collecting',v_collecting),
    'indicators',coalesce(v_base->'indicators','[]'::jsonb)||jsonb_build_array(v_indicator),
    'alerts',case when v_state in('critical','warning') then coalesce(v_base->'alerts','[]'::jsonb)||jsonb_build_array(v_indicator) else coalesce(v_base->'alerts','[]'::jsonb) end,
    'maintenance_evidence',v_evidence
  );
end;
$$;
revoke all on function private.get_crypto_admin_operational_summary() from public,anon;
grant execute on function private.get_crypto_admin_operational_summary() to authenticated,service_role;

select cron.unschedule(jobid) from cron.job where jobname='crypto-lab-maintenance-evidence-seal';
select cron.schedule(
  'crypto-lab-maintenance-evidence-seal','27 * * * *',
  $$select private.service_seal_latest_crypto_maintenance(null,timestamptz '2026-08-05 03:17:00+00')$$
);

notify pgrst,'reload schema';