create table if not exists public.crypto_release_manifests(
  id bigint generated by default as identity primary key,
  manifest_key text not null unique,
  build text not null,
  manifest jsonb not null,
  source_commit text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint crypto_release_manifests_key_chk check(manifest_key ~ '^[a-z0-9._-]{3,80}$'),
  constraint crypto_release_manifests_build_chk check(build ~ '^[0-9]{4,10}$'),
  constraint crypto_release_manifests_manifest_object_chk check(jsonb_typeof(manifest)='object')
);
create unique index if not exists crypto_release_manifests_one_active_build_idx on public.crypto_release_manifests(build) where active;

create table if not exists public.crypto_release_drift_observations(
  id bigint generated by default as identity primary key,
  manifest_id bigint not null references public.crypto_release_manifests(id) on delete restrict,
  source text not null default 'automation',
  repository_head_sha text,
  application_commit text not null,
  root_v78_sha text not null,
  pwa_cache text not null,
  edge_functions jsonb not null default '[]'::jsonb,
  assets jsonb not null default '[]'::jsonb,
  note text,
  observed_at timestamptz not null default now(),
  constraint crypto_release_drift_source_chk check(source in('automation','operator','release')),
  constraint crypto_release_drift_sha_chk check(application_commit ~ '^[0-9a-f]{40}$' and root_v78_sha ~ '^[0-9a-f]{40}$'),
  constraint crypto_release_drift_head_chk check(repository_head_sha is null or repository_head_sha ~ '^[0-9a-f]{40}$'),
  constraint crypto_release_drift_edge_array_chk check(jsonb_typeof(edge_functions)='array'),
  constraint crypto_release_drift_assets_array_chk check(jsonb_typeof(assets)='array'),
  constraint crypto_release_drift_note_chk check(note is null or char_length(note)<=500)
);
create index if not exists crypto_release_drift_manifest_time_idx on public.crypto_release_drift_observations(manifest_id,observed_at desc);

create table if not exists public.crypto_rollback_rehearsals(
  id bigint generated by default as identity primary key,
  manifest_id bigint not null references public.crypto_release_manifests(id) on delete restrict,
  candidate_checkpoint_id bigint references public.crypto_release_checkpoints(id) on delete set null,
  rollback_target_sha text not null,
  result text not null,
  metadata_only boolean not null default true,
  checks jsonb not null default '[]'::jsonb,
  note text,
  rehearsed_at timestamptz not null default now(),
  constraint crypto_rollback_target_sha_chk check(rollback_target_sha ~ '^[0-9a-f]{40}$'),
  constraint crypto_rollback_result_chk check(result in('passed','warning','failed')),
  constraint crypto_rollback_checks_array_chk check(jsonb_typeof(checks)='array'),
  constraint crypto_rollback_note_chk check(note is null or char_length(note)<=500)
);
create index if not exists crypto_rollback_rehearsals_manifest_time_idx on public.crypto_rollback_rehearsals(manifest_id,rehearsed_at desc);

alter table public.crypto_release_manifests enable row level security;
alter table public.crypto_release_drift_observations enable row level security;
alter table public.crypto_rollback_rehearsals enable row level security;

drop policy if exists crypto_release_manifests_service_only on public.crypto_release_manifests;
create policy crypto_release_manifests_service_only on public.crypto_release_manifests for all to service_role using(true) with check(true);
drop policy if exists crypto_release_drift_service_only on public.crypto_release_drift_observations;
create policy crypto_release_drift_service_only on public.crypto_release_drift_observations for all to service_role using(true) with check(true);
drop policy if exists crypto_rollback_rehearsals_service_only on public.crypto_rollback_rehearsals;
create policy crypto_rollback_rehearsals_service_only on public.crypto_rollback_rehearsals for all to service_role using(true) with check(true);

revoke all on public.crypto_release_manifests from public,anon,authenticated;
revoke all on public.crypto_release_drift_observations from public,anon,authenticated;
revoke all on public.crypto_rollback_rehearsals from public,anon,authenticated;
grant all on public.crypto_release_manifests to service_role;
grant all on public.crypto_release_drift_observations to service_role;
grant all on public.crypto_rollback_rehearsals to service_role;

insert into public.crypto_release_manifests(manifest_key,build,manifest,source_commit,active)
values(
  'crypto-lab-v79-7930-drift1','7930',
  $manifest${
    "schema_version":1,
    "project_ref":"txhzxbizjpinowepfjkm",
    "build":"7930",
    "stable_root":{"path":"index.html","sha":"4a278c891d37b3760ec1ac988690ea9ad587b24e"},
    "application":{"application_commit":"bfa7875e34f51e47c134b4c570c141298d904ea7","evidence_commit":"cc1fc516e39ace6aedbfbf86adad080ab3da15cd","pwa_cache":"crypto-lab-v79-7930-integrity1","assets":[
      {"path":"v79/index.html","sha":"b92335b3a3d76e349f1845fd653e1c1021d6d7f6","marker":"app.html?v=7930"},
      {"path":"v79/app.html","sha":"432fe33542bf58b41bab590caf0fcf5d635f8da4","marker":"commercial-extension.js?v=7930"},
      {"path":"v79/commercial-extension.js","sha":"794360f0aed722ab5b72e9305909f1bbe61388b0","marker":"adminDataIntegrityScript"},
      {"path":"v79/service-worker.js","sha":"245f01bb2d2664ea953fb6724321faa3ef999081","marker":"crypto-lab-v79-7930-integrity1"},
      {"path":"v79/admin-integrity.js","sha":"0e5fee3828021025e391cefbd2e5c12d56bed283","marker":"get_crypto_admin_data_integrity"},
      {"path":"v79/admin-ops-summary.js","sha":"afab225a2029618ee0cde83f7fae1101f3a33fa9","marker":"get_crypto_admin_operational_summary"}
    ]},
    "migrations":[
      {"version":"20260804122547","name":"merge_crypto_operational_slo_maintenance_retention"},
      {"version":"20260804123221","name":"consolidate_operational_slo_capture"},
      {"version":"20260804132610","name":"harden_operational_http_reconciliation"},
      {"version":"20260804145557","name":"crypto_operational_escalation_summary"},
      {"version":"20260804145929","name":"fix_operational_summary_crypto_table_pattern"},
      {"version":"20260804150038","name":"fix_operational_summary_false_positive_thresholds"},
      {"version":"20260804154500","name":"crypto_admin_continuous_data_integrity"}
    ],
    "edge_functions":[
      {"slug":"crypto-ai-advisor","version":9,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-telegram-signal","version":5,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-signal-monitor","version":6,"verify_jwt":false,"status":"ACTIVE"},
      {"slug":"crypto-signal-register","version":7,"verify_jwt":false,"status":"ACTIVE"},
      {"slug":"crypto-market-scanner","version":12,"verify_jwt":false,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-preview","version":5,"verify_jwt":false,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-chart","version":2,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-publisher","version":5,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-validator","version":61,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-backtest-data","version":4,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-scanner","version":1,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-backtest","version":2,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-backtest-run","version":1,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-mail-dispatch","version":2,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-register","version":2,"verify_jwt":false,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-data-export","version":4,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-recover","version":1,"verify_jwt":false,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-admin-deletions","version":4,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-commercial","version":1,"verify_jwt":true,"status":"ACTIVE"},
      {"slug":"crypto-lab-v79-billing-webhook","version":1,"verify_jwt":false,"status":"ACTIVE"}
    ],
    "release_evidence":{"release_gate_run_id":"30926170428","browser_smoke_run_id":"30926174066","pages_run_id":"30926169393","technical_score":100,"commercial_score":60}
  }$manifest$::jsonb,
  'bd0b189e560fa8dd1d1c83e1c9665e987373d678',true
)
on conflict(manifest_key) do update set manifest=excluded.manifest,source_commit=excluded.source_commit,active=true;

create or replace function private.service_record_crypto_release_drift_observation(
  p_manifest_key text,p_repository_head_sha text,p_application_commit text,p_root_v78_sha text,p_pwa_cache text,
  p_edge_functions jsonb,p_assets jsonb,p_source text default 'automation',p_note text default null
) returns bigint language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_manifest_id bigint; v_id bigint;
begin
  select id into v_manifest_id from public.crypto_release_manifests where manifest_key=p_manifest_key and active;
  if v_manifest_id is null then raise exception 'Active release manifest not found' using errcode='22023'; end if;
  if p_source not in('automation','operator','release') then raise exception 'Invalid observation source' using errcode='22023'; end if;
  if p_application_commit !~ '^[0-9a-f]{40}$' or p_root_v78_sha !~ '^[0-9a-f]{40}$' then raise exception 'Invalid SHA' using errcode='22023'; end if;
  if p_repository_head_sha is not null and p_repository_head_sha !~ '^[0-9a-f]{40}$' then raise exception 'Invalid repository head SHA' using errcode='22023'; end if;
  if jsonb_typeof(p_edge_functions)<>'array' or jsonb_typeof(p_assets)<>'array' then raise exception 'Observation arrays required' using errcode='22023'; end if;
  if p_note is not null and char_length(p_note)>500 then raise exception 'Observation note too long' using errcode='22023'; end if;
  insert into public.crypto_release_drift_observations(manifest_id,source,repository_head_sha,application_commit,root_v78_sha,pwa_cache,edge_functions,assets,note)
  values(v_manifest_id,p_source,p_repository_head_sha,p_application_commit,p_root_v78_sha,p_pwa_cache,p_edge_functions,p_assets,p_note) returning id into v_id;
  return v_id;
end;$$;
revoke all on function private.service_record_crypto_release_drift_observation(text,text,text,text,text,jsonb,jsonb,text,text) from public,anon,authenticated;
grant execute on function private.service_record_crypto_release_drift_observation(text,text,text,text,text,jsonb,jsonb,text,text) to service_role;

create or replace function private.crypto_release_drift_snapshot()
returns jsonb language plpgsql stable security definer set search_path=public,private,supabase_migrations,pg_catalog,pg_temp as $$
declare
  v_manifest public.crypto_release_manifests%rowtype;
  v_observation public.crypto_release_drift_observations%rowtype;
  v_release public.crypto_release_checkpoints%rowtype;
  v_checks jsonb:='[]'::jsonb; v_violations jsonb:='[]'::jsonb;
  v_critical integer:=0; v_warning integer:=0; v_item jsonb; v_actual jsonb; v_pass boolean; v_detail text; v_age_minutes numeric; v_release_pass boolean;
begin
  select * into v_manifest from public.crypto_release_manifests where active order by id desc limit 1;
  if v_manifest.id is null then
    return jsonb_build_object('state','critical','generated_at',now(),'critical_checks',1,'warning_checks',0,'checks',jsonb_build_array(jsonb_build_object('code','manifest_missing','severity','critical','passed',false,'detail','Active release manifest is missing')),'violations',jsonb_build_array(jsonb_build_object('code','manifest_missing','severity','critical','detail','Active release manifest is missing')));
  end if;
  select * into v_observation from public.crypto_release_drift_observations where manifest_id=v_manifest.id order by observed_at desc,id desc limit 1;
  select * into v_release from public.crypto_release_checkpoints order by id desc limit 1;
  for v_item in select value from jsonb_array_elements(coalesce(v_manifest.manifest->'migrations','[]'::jsonb)) loop
    select exists(select 1 from supabase_migrations.schema_migrations where version=v_item->>'version' and name=v_item->>'name') into v_pass;
    v_detail:='Applied migration '||(v_item->>'version')||' / '||(v_item->>'name');
    v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','migration:'||(v_item->>'name'),'severity','critical','passed',v_pass,'detail',v_detail));
    if not v_pass then v_critical:=v_critical+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','migration:'||(v_item->>'name'),'severity','critical','detail',v_detail));end if;
  end loop;
  if v_observation.id is null then
    v_critical:=v_critical+1;
    v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','observation_missing','severity','critical','passed',false,'detail','No release drift observation exists'));
    v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','observation_missing','severity','critical','detail','No release drift observation exists'));
  else
    v_age_minutes:=round((extract(epoch from(now()-v_observation.observed_at))/60.0)::numeric,1);
    v_pass:=v_age_minutes<=120;
    v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','observation_freshness','severity','warning','passed',v_pass,'detail','Latest observation age minutes: '||v_age_minutes));
    if not v_pass then v_warning:=v_warning+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','observation_freshness','severity','warning','detail','Latest observation is older than two hours'));end if;
    v_pass:=v_observation.root_v78_sha=coalesce(v_manifest.manifest#>>'{stable_root,sha}','');
    v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','stable_root_sha','severity','critical','passed',v_pass,'detail','Stable root v78 SHA matches manifest'));
    if not v_pass then v_critical:=v_critical+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','stable_root_sha','severity','critical','detail','Stable root v78 SHA drift detected'));end if;
    v_pass:=v_observation.application_commit=coalesce(v_manifest.manifest#>>'{application,application_commit}','');
    v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','application_commit','severity','critical','passed',v_pass,'detail','Observed application commit matches manifest'));
    if not v_pass then v_critical:=v_critical+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','application_commit','severity','critical','detail','Application commit drift detected'));end if;
    v_pass:=v_observation.pwa_cache=coalesce(v_manifest.manifest#>>'{application,pwa_cache}','');
    v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','pwa_cache','severity','critical','passed',v_pass,'detail','Observed PWA cache matches manifest'));
    if not v_pass then v_critical:=v_critical+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','pwa_cache','severity','critical','detail','PWA cache drift detected'));end if;
    for v_item in select value from jsonb_array_elements(coalesce(v_manifest.manifest->'edge_functions','[]'::jsonb)) loop
      select value into v_actual from jsonb_array_elements(v_observation.edge_functions) where value->>'slug'=v_item->>'slug' limit 1;
      v_pass:=v_actual is not null and coalesce((v_actual->>'version')::integer,-1)=coalesce((v_item->>'version')::integer,-2) and coalesce((v_actual->>'verify_jwt')::boolean,false)=coalesce((v_item->>'verify_jwt')::boolean,false) and coalesce(v_actual->>'status','')=coalesce(v_item->>'status','');
      v_detail:='Edge '||(v_item->>'slug')||' expected v'||(v_item->>'version')||' jwt='||(v_item->>'verify_jwt');
      v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','edge:'||(v_item->>'slug'),'severity','critical','passed',v_pass,'detail',v_detail));
      if not v_pass then v_critical:=v_critical+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','edge:'||(v_item->>'slug'),'severity','critical','detail',v_detail));end if;
    end loop;
    for v_item in select value from jsonb_array_elements(coalesce(v_manifest.manifest#>'{application,assets}','[]'::jsonb)) loop
      select value into v_actual from jsonb_array_elements(v_observation.assets) where value->>'path'=v_item->>'path' limit 1;
      v_pass:=v_actual is not null and coalesce(v_actual->>'sha','')=coalesce(v_item->>'sha','') and coalesce((v_actual->>'marker_ok')::boolean,false);
      v_detail:='Asset '||(v_item->>'path')||' SHA and marker match manifest';
      v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','asset:'||(v_item->>'path'),'severity','critical','passed',v_pass,'detail',v_detail));
      if not v_pass then v_critical:=v_critical+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','asset:'||(v_item->>'path'),'severity','critical','detail',v_detail));end if;
    end loop;
  end if;
  v_release_pass:=v_release.id is not null and v_release.build=v_manifest.build and coalesce(v_release.release_gate_run_id,'')=coalesce(v_manifest.manifest#>>'{release_evidence,release_gate_run_id}','') and coalesce(v_release.browser_smoke_run_id,'')=coalesce(v_manifest.manifest#>>'{release_evidence,browser_smoke_run_id}','') and coalesce(v_release.pages_run_id,'')=coalesce(v_manifest.manifest#>>'{release_evidence,pages_run_id}','');
  v_checks:=v_checks||jsonb_build_array(jsonb_build_object('code','release_checkpoint_evidence','severity','critical','passed',v_release_pass,'detail','Latest checkpoint evidence matches release manifest'));
  if not v_release_pass then v_critical:=v_critical+1;v_violations:=v_violations||jsonb_build_array(jsonb_build_object('code','release_checkpoint_evidence','severity','critical','detail','Release checkpoint evidence drift detected'));end if;
  return jsonb_build_object('state',case when v_critical>0 then 'critical' when v_warning>0 then 'warning' else 'healthy' end,'generated_at',now(),'manifest_key',v_manifest.manifest_key,'build',v_manifest.build,'manifest_source_commit',v_manifest.source_commit,'observation_id',v_observation.id,'observed_at',v_observation.observed_at,'repository_head_sha',v_observation.repository_head_sha,'critical_checks',v_critical,'warning_checks',v_warning,'total_checks',jsonb_array_length(v_checks),'checks',v_checks,'violations',v_violations);
end;$$;

create or replace function private.get_crypto_admin_release_drift() returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$begin if not public.crypto_is_admin() then raise exception 'Admin access required' using errcode='42501';end if;return private.crypto_release_drift_snapshot();end;$$;
create or replace function public.get_crypto_admin_release_drift() returns jsonb language sql stable security invoker set search_path=public,private,pg_temp as $$select private.get_crypto_admin_release_drift()$$;
revoke all on function private.crypto_release_drift_snapshot() from public,anon,authenticated;
revoke all on function private.get_crypto_admin_release_drift() from public,anon;
grant execute on function private.crypto_release_drift_snapshot() to service_role;
grant execute on function private.get_crypto_admin_release_drift() to authenticated,service_role;
revoke all on function public.get_crypto_admin_release_drift() from public,anon;
grant execute on function public.get_crypto_admin_release_drift() to authenticated,service_role;

create or replace function private.service_record_crypto_rollback_rehearsal(p_manifest_key text,p_candidate_checkpoint_id bigint,p_rollback_target_sha text,p_result text,p_checks jsonb,p_note text default null)
returns bigint language plpgsql security definer set search_path=public,private,pg_temp as $$declare v_manifest_id bigint;v_id bigint;begin
  select id into v_manifest_id from public.crypto_release_manifests where manifest_key=p_manifest_key and active;
  if v_manifest_id is null then raise exception 'Active release manifest not found' using errcode='22023';end if;
  if p_rollback_target_sha !~ '^[0-9a-f]{40}$' then raise exception 'Invalid rollback target SHA' using errcode='22023';end if;
  if p_result not in('passed','warning','failed') then raise exception 'Invalid rehearsal result' using errcode='22023';end if;
  if jsonb_typeof(p_checks)<>'array' then raise exception 'Checks array required' using errcode='22023';end if;
  if p_note is not null and char_length(p_note)>500 then raise exception 'Rehearsal note too long' using errcode='22023';end if;
  insert into public.crypto_rollback_rehearsals(manifest_id,candidate_checkpoint_id,rollback_target_sha,result,metadata_only,checks,note) values(v_manifest_id,p_candidate_checkpoint_id,p_rollback_target_sha,p_result,true,p_checks,p_note) returning id into v_id;return v_id;
end;$$;

create or replace function private.get_crypto_admin_rollback_readiness() returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$declare v_row public.crypto_rollback_rehearsals%rowtype;begin
  if not public.crypto_is_admin() then raise exception 'Admin access required' using errcode='42501';end if;
  select * into v_row from public.crypto_rollback_rehearsals order by rehearsed_at desc,id desc limit 1;
  if v_row.id is null then return jsonb_build_object('state','warning','reason','No rollback rehearsal recorded');end if;
  return jsonb_build_object('state',case when v_row.result='passed' then 'healthy' when v_row.result='warning' then 'warning' else 'critical' end,'id',v_row.id,'result',v_row.result,'metadata_only',v_row.metadata_only,'rollback_target_sha',v_row.rollback_target_sha,'candidate_checkpoint_id',v_row.candidate_checkpoint_id,'checks',v_row.checks,'note',v_row.note,'rehearsed_at',v_row.rehearsed_at);
end;$$;
create or replace function public.get_crypto_admin_rollback_readiness() returns jsonb language sql stable security invoker set search_path=public,private,pg_temp as $$select private.get_crypto_admin_rollback_readiness()$$;
revoke all on function private.service_record_crypto_rollback_rehearsal(text,bigint,text,text,jsonb,text) from public,anon,authenticated;
grant execute on function private.service_record_crypto_rollback_rehearsal(text,bigint,text,text,jsonb,text) to service_role;
revoke all on function private.get_crypto_admin_rollback_readiness() from public,anon;
grant execute on function private.get_crypto_admin_rollback_readiness() to authenticated,service_role;
revoke all on function public.get_crypto_admin_rollback_readiness() from public,anon;
grant execute on function public.get_crypto_admin_rollback_readiness() to authenticated,service_role;

do $$begin if to_regprocedure('private.get_crypto_admin_operational_summary_drift_base()') is null then alter function private.get_crypto_admin_operational_summary() rename to get_crypto_admin_operational_summary_drift_base;end if;end;$$;

create or replace function private.get_crypto_admin_operational_summary()
returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$
declare v_base jsonb;v_drift jsonb;v_indicator jsonb;v_state text;v_base_state text;v_counts jsonb;v_healthy integer;v_warning integer;v_critical integer;v_collecting integer;
begin
  if not public.crypto_is_admin() then raise exception 'Admin access required' using errcode='42501';end if;
  v_base:=private.get_crypto_admin_operational_summary_drift_base();v_drift:=private.crypto_release_drift_snapshot();v_state:=coalesce(v_drift->>'state','critical');v_base_state:=coalesce(v_base->>'overall_state','critical');
  v_indicator:=jsonb_build_object('code','release_drift','state',v_state,'owner','release','action_code','release_drift_runbook','metrics',jsonb_build_object('total_checks',v_drift->'total_checks','critical_checks',v_drift->'critical_checks','warning_checks',v_drift->'warning_checks','manifest_key',v_drift->'manifest_key','observed_at',v_drift->'observed_at'));
  v_counts:=coalesce(v_base->'counts','{}'::jsonb);v_healthy:=coalesce((v_counts->>'healthy')::integer,0)+(case when v_state='healthy' then 1 else 0 end);v_warning:=coalesce((v_counts->>'warning')::integer,0)+(case when v_state='warning' then 1 else 0 end);v_critical:=coalesce((v_counts->>'critical')::integer,0)+(case when v_state='critical' then 1 else 0 end);v_collecting:=coalesce((v_counts->>'collecting')::integer,0)+(case when v_state='collecting' then 1 else 0 end);
  return v_base||jsonb_build_object('overall_state',case when v_base_state='critical' or v_state='critical' then 'critical' when v_base_state='warning' or v_state='warning' then 'warning' when v_base_state='collecting' or v_state='collecting' then 'collecting' else 'healthy' end,'decision',case when v_base_state='critical' or v_state='critical' then 'NO_GO' when v_base_state in('warning','collecting') or v_state in('warning','collecting') then 'WATCH' else 'TECHNICAL_GO' end,'counts',jsonb_build_object('healthy',v_healthy,'warning',v_warning,'critical',v_critical,'collecting',v_collecting),'indicators',coalesce(v_base->'indicators','[]'::jsonb)||jsonb_build_array(v_indicator),'alerts',case when v_state in('critical','warning') then coalesce(v_base->'alerts','[]'::jsonb)||jsonb_build_array(v_indicator) else coalesce(v_base->'alerts','[]'::jsonb) end,'release_drift',v_drift);
end;$$;
revoke all on function private.get_crypto_admin_operational_summary() from public,anon;
grant execute on function private.get_crypto_admin_operational_summary() to authenticated,service_role;
notify pgrst,'reload schema';
