create table if not exists public.crypto_prelaunch_monitor_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  window_minutes integer not null default 60 check (window_minutes between 5 and 1440),
  operational_requests integer not null default 0,
  operational_failures integer not null default 0,
  operational_5xx integer not null default 0,
  operational_429 integer not null default 0,
  max_duration_ms bigint,
  open_incidents integer not null default 0,
  billing_orders integer not null default 0,
  billing_events integer not null default 0,
  open_billing_anomalies integer not null default 0,
  onchain_claims integer not null default 0,
  registration_attempts integer not null default 0,
  recovery_attempts integer not null default 0,
  risky_admin_actions integer not null default 0,
  suspicious_score integer not null default 0,
  status text not null check (status in ('clean','degraded','alert')),
  details jsonb not null default '{}'::jsonb
);

alter table public.crypto_prelaunch_monitor_snapshots enable row level security;
revoke all on table public.crypto_prelaunch_monitor_snapshots from public, anon, authenticated;
grant select, insert on table public.crypto_prelaunch_monitor_snapshots to service_role;

create index if not exists crypto_prelaunch_monitor_snapshots_captured_idx
  on public.crypto_prelaunch_monitor_snapshots (captured_at desc);

create or replace function public.crypto_capture_prelaunch_monitor_snapshot(p_window_minutes integer default 60)
returns public.crypto_prelaunch_monitor_snapshots
language plpgsql
security definer
set search_path = public
as $$
declare
  v_since timestamptz := now() - make_interval(mins => greatest(5, least(coalesce(p_window_minutes,60),1440)));
  v_row public.crypto_prelaunch_monitor_snapshots;
  v_operational_requests integer;
  v_operational_failures integer;
  v_operational_5xx integer;
  v_operational_429 integer;
  v_max_duration_ms bigint;
  v_open_incidents integer;
  v_billing_orders integer;
  v_billing_events integer;
  v_open_billing_anomalies integer;
  v_onchain_claims integer;
  v_registration_attempts integer;
  v_recovery_attempts integer;
  v_risky_admin_actions integer;
  v_score integer;
  v_status text;
begin
  select count(*)::int,
         count(*) filter (where not coalesce(success,false))::int,
         count(*) filter (where status_code >= 500)::int,
         count(*) filter (where status_code = 429)::int,
         max(duration_ms)
    into v_operational_requests, v_operational_failures, v_operational_5xx, v_operational_429, v_max_duration_ms
    from public.crypto_operational_http_requests
   where requested_at >= v_since;

  select count(*)::int into v_open_incidents
    from public.crypto_operational_incidents
   where status <> 'resolved';

  select count(*)::int into v_billing_orders
    from public.crypto_billing_orders
   where created_at >= v_since;

  select count(*)::int into v_billing_events
    from public.crypto_billing_events
   where created_at >= v_since;

  select count(*)::int into v_open_billing_anomalies
    from public.crypto_billing_anomalies
   where status <> 'resolved';

  select count(*)::int into v_onchain_claims
    from public.crypto_onchain_tx_claims
   where created_at >= v_since;

  select count(*)::int into v_registration_attempts
    from public.crypto_registration_attempts
   where created_at >= v_since;

  select count(*)::int into v_recovery_attempts
    from public.crypto_recovery_attempts
   where created_at >= v_since;

  select count(*)::int into v_risky_admin_actions
    from public.crypto_admin_audit_log
   where created_at >= v_since
     and severity in ('high','critical')
     and coalesce(actor_role,'') not in ('service_role','automation_service');

  v_score :=
      coalesce(v_operational_failures,0)
    + coalesce(v_operational_5xx,0) * 2
    + coalesce(v_operational_429,0)
    + coalesce(v_open_incidents,0) * 10
    + coalesce(v_billing_orders,0) * 20
    + coalesce(v_billing_events,0) * 20
    + coalesce(v_open_billing_anomalies,0) * 25
    + coalesce(v_onchain_claims,0) * 25
    + coalesce(v_registration_attempts,0) * 15
    + coalesce(v_recovery_attempts,0) * 10
    + coalesce(v_risky_admin_actions,0) * 25;

  if coalesce(v_billing_orders,0) > 0
     or coalesce(v_billing_events,0) > 0
     or coalesce(v_open_billing_anomalies,0) > 0
     or coalesce(v_onchain_claims,0) > 0
     or coalesce(v_registration_attempts,0) > 0
     or coalesce(v_recovery_attempts,0) > 0
     or coalesce(v_risky_admin_actions,0) > 0 then
    v_status := 'alert';
  elsif coalesce(v_open_incidents,0) > 0
     or coalesce(v_operational_failures,0) > 2
     or coalesce(v_operational_5xx,0) > 1 then
    v_status := 'degraded';
  else
    v_status := 'clean';
  end if;

  insert into public.crypto_prelaunch_monitor_snapshots (
    window_minutes, operational_requests, operational_failures, operational_5xx,
    operational_429, max_duration_ms, open_incidents, billing_orders, billing_events,
    open_billing_anomalies, onchain_claims, registration_attempts, recovery_attempts,
    risky_admin_actions, suspicious_score, status, details
  ) values (
    greatest(5, least(coalesce(p_window_minutes,60),1440)),
    coalesce(v_operational_requests,0), coalesce(v_operational_failures,0),
    coalesce(v_operational_5xx,0), coalesce(v_operational_429,0), v_max_duration_ms,
    coalesce(v_open_incidents,0), coalesce(v_billing_orders,0), coalesce(v_billing_events,0),
    coalesce(v_open_billing_anomalies,0), coalesce(v_onchain_claims,0),
    coalesce(v_registration_attempts,0), coalesce(v_recovery_attempts,0),
    coalesce(v_risky_admin_actions,0), v_score, v_status,
    jsonb_build_object(
      'mode','closed_prelaunch',
      'payments_expected',false,
      'registration_expected',false,
      'mainnet_expected',false,
      'alert_contract','Any billing/onchain claim/registration/recovery/risky-admin activity before owner authorization is an alert.'
    )
  ) returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.crypto_capture_prelaunch_monitor_snapshot(integer) from public, anon, authenticated;
grant execute on function public.crypto_capture_prelaunch_monitor_snapshot(integer) to service_role;

comment on table public.crypto_prelaunch_monitor_snapshots is 'Fail-closed commercial prelaunch monitoring snapshots. No production activation side effects.';
comment on function public.crypto_capture_prelaunch_monitor_snapshot(integer) is 'Service-role-only passive monitoring snapshot; never activates registration, billing, mainnet, refunds, or paid entitlements.';
