create table if not exists public.crypto_operational_http_requests(
  request_id bigint primary key,
  source_name text not null check(source_name in('crypto-signal-monitor','crypto-market-scanner')),
  requested_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists crypto_operational_http_requests_pending_idx
on public.crypto_operational_http_requests(requested_at)
where processed_at is null;

alter table public.crypto_operational_http_requests enable row level security;
revoke all on table public.crypto_operational_http_requests from public,anon,authenticated;
grant select,insert,update,delete on table public.crypto_operational_http_requests to service_role;

create table if not exists public.crypto_operational_incidents(
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  source_type text not null check(source_type in('edge','cron')),
  source_name text not null,
  status text not null default 'open' check(status in('open','resolved')),
  severity text not null default 'high' check(severity in('low','medium','high','critical')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  occurrences integer not null default 1 check(occurrences>0),
  last_observation_id text,
  last_status_code integer,
  last_error text,
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crypto_operational_incidents_status_seen_idx
on public.crypto_operational_incidents(status,last_seen_at desc);

alter table public.crypto_operational_incidents enable row level security;
revoke all on table public.crypto_operational_incidents from public,anon,authenticated;
grant select,insert,update,delete on table public.crypto_operational_incidents to service_role;
grant usage,select on sequence public.crypto_operational_incidents_id_seq to service_role;

create or replace function private.track_crypto_operational_http_request(p_source_name text,p_request_id bigint)
returns bigint
language plpgsql
security definer
set search_path to 'public','private','pg_temp'
as $$
begin
  if p_source_name not in('crypto-signal-monitor','crypto-market-scanner') then
    raise exception 'Unsupported operational source' using errcode='22023';
  end if;
  if p_request_id is null then
    raise exception 'Request id is required' using errcode='22023';
  end if;
  insert into public.crypto_operational_http_requests(request_id,source_name)
  values(p_request_id,p_source_name)
  on conflict(request_id) do nothing;
  return p_request_id;
end;
$$;

create or replace function private.reconcile_crypto_operational_incidents()
returns jsonb
language plpgsql
security definer
set search_path to 'public','private','cron','net','pg_temp'
as $$
declare
  v_edge record;
  v_cron record;
  v_failed boolean;
  v_fingerprint text;
  v_observation text;
  v_opened integer:=0;
  v_resolved integer:=0;
  v_processed integer:=0;
begin
  for v_edge in
    select q.request_id,q.source_name,q.requested_at,r.status_code,r.timed_out,r.error_msg,r.content
    from public.crypto_operational_http_requests q
    left join net._http_response r on r.id=q.request_id
    where q.processed_at is null
      and (r.id is not null or q.requested_at<now()-interval '2 minutes')
    order by q.requested_at
    limit 200
  loop
    v_fingerprint:='edge:'||v_edge.source_name;
    v_observation:=v_edge.request_id::text;
    v_failed:=v_edge.status_code is null
      or coalesce(v_edge.timed_out,false)
      or v_edge.error_msg is not null
      or v_edge.status_code<200
      or v_edge.status_code>=300
      or coalesce(v_edge.content,'') like '%"success":false%';

    if v_failed then
      insert into public.crypto_operational_incidents(
        fingerprint,source_type,source_name,status,severity,first_seen_at,last_seen_at,occurrences,last_observation_id,last_status_code,last_error,resolved_at,resolution_note
      ) values (
        v_fingerprint,'edge',v_edge.source_name,'open','high',v_edge.requested_at,now(),1,v_observation,v_edge.status_code,
        case
          when v_edge.status_code is null then 'No HTTP response within two minutes'
          when coalesce(v_edge.timed_out,false) then 'HTTP request timed out'
          when v_edge.error_msg is not null then 'HTTP transport error'
          when v_edge.status_code<200 or v_edge.status_code>=300 then 'HTTP status '||v_edge.status_code::text
          else 'Edge Function returned success=false'
        end,
        null,null
      )
      on conflict(fingerprint) do update set
        status='open',severity='high',
        first_seen_at=case when public.crypto_operational_incidents.status='resolved' then excluded.first_seen_at else public.crypto_operational_incidents.first_seen_at end,
        last_seen_at=excluded.last_seen_at,
        occurrences=case when public.crypto_operational_incidents.status='resolved' then 1 else public.crypto_operational_incidents.occurrences+1 end,
        last_observation_id=excluded.last_observation_id,
        last_status_code=excluded.last_status_code,
        last_error=excluded.last_error,
        resolved_at=null,resolution_note=null,updated_at=now()
      where public.crypto_operational_incidents.last_observation_id is distinct from excluded.last_observation_id;
      if found then v_opened:=v_opened+1; end if;
    else
      update public.crypto_operational_incidents
      set status='resolved',resolved_at=now(),resolution_note='Recovered on successful Edge response',
          last_observation_id=v_observation,last_status_code=v_edge.status_code,last_error=null,last_seen_at=now(),updated_at=now()
      where fingerprint=v_fingerprint and status='open' and last_observation_id is distinct from v_observation;
      if found then v_resolved:=v_resolved+1; end if;
    end if;

    update public.crypto_operational_http_requests set processed_at=now() where request_id=v_edge.request_id;
    v_processed:=v_processed+1;
  end loop;

  for v_cron in
    select j.jobid,j.jobname,r.status,r.start_time,r.end_time
    from cron.job j
    join lateral(
      select d.status,d.start_time,d.end_time
      from cron.job_run_details d
      where d.jobid=j.jobid
        and d.start_time is not null
        and d.status in('succeeded','failed')
      order by d.start_time desc nulls last
      limit 1
    ) r on true
    where j.jobname in(
      'crypto-signal-monitor-every-minute','crypto-market-scanner-every-15-minutes',
      'crypto-lab-daily-maintenance','crypto-lab-subscription-lifecycle',
      'crypto-lab-billing-event-retry','crypto-lab-billing-reconciliation'
    )
  loop
    v_fingerprint:='cron:'||v_cron.jobname;
    v_observation:=v_cron.jobid::text||':'||extract(epoch from v_cron.start_time)::bigint::text;
    if v_cron.status='failed' then
      insert into public.crypto_operational_incidents(
        fingerprint,source_type,source_name,status,severity,first_seen_at,last_seen_at,occurrences,last_observation_id,last_error
      ) values (
        v_fingerprint,'cron',v_cron.jobname,'open','high',v_cron.start_time,now(),1,v_observation,'Cron terminal status failed'
      )
      on conflict(fingerprint) do update set
        status='open',severity='high',
        first_seen_at=case when public.crypto_operational_incidents.status='resolved' then excluded.first_seen_at else public.crypto_operational_incidents.first_seen_at end,
        last_seen_at=excluded.last_seen_at,
        occurrences=case when public.crypto_operational_incidents.status='resolved' then 1 else public.crypto_operational_incidents.occurrences+1 end,
        last_observation_id=excluded.last_observation_id,last_error=excluded.last_error,
        resolved_at=null,resolution_note=null,updated_at=now()
      where public.crypto_operational_incidents.last_observation_id is distinct from excluded.last_observation_id;
      if found then v_opened:=v_opened+1; end if;
    else
      update public.crypto_operational_incidents
      set status='resolved',resolved_at=now(),resolution_note='Recovered on successful cron execution',
          last_observation_id=v_observation,last_error=null,last_seen_at=now(),updated_at=now()
      where fingerprint=v_fingerprint and status='open' and last_observation_id is distinct from v_observation;
      if found then v_resolved:=v_resolved+1; end if;
    end if;
  end loop;

  delete from public.crypto_operational_http_requests where processed_at<now()-interval '30 days';
  delete from public.crypto_operational_incidents where status='resolved' and resolved_at<now()-interval '180 days';

  return jsonb_build_object(
    'success',true,'http_requests_processed',v_processed,'incidents_opened_or_updated',v_opened,
    'incidents_resolved',v_resolved,
    'open_incidents',(select count(*) from public.crypto_operational_incidents where status='open'),
    'resolved_incidents',(select count(*) from public.crypto_operational_incidents where status='resolved')
  );
end;
$$;

revoke all on function private.track_crypto_operational_http_request(text,bigint) from public,anon,authenticated;
revoke all on function private.reconcile_crypto_operational_incidents() from public,anon,authenticated;
grant execute on function private.track_crypto_operational_http_request(text,bigint) to service_role;
grant execute on function private.reconcile_crypto_operational_incidents() to service_role;

do $$
begin
  perform cron.unschedule('crypto-signal-monitor-every-minute');
  perform cron.schedule(
    'crypto-signal-monitor-every-minute','* * * * *',$cmd$
      with request as (
        select net.http_post(
          url := 'https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-signal-monitor',
          headers := jsonb_build_object(
            'Content-Type','application/json',
            'x-monitor-secret',(
              select decrypted_secret from vault.decrypted_secrets
              where name='MONITOR_SECRET'
              order by updated_at desc,created_at desc limit 1
            )
          ),
          body := '{}'::jsonb,
          timeout_milliseconds := 15000
        ) as request_id
      )
      select private.track_crypto_operational_http_request('crypto-signal-monitor',request_id) from request;
    $cmd$
  );

  perform cron.unschedule('crypto-market-scanner-every-15-minutes');
  perform cron.schedule(
    'crypto-market-scanner-every-15-minutes','*/15 * * * *',$cmd$
      with request as (
        select net.http_post(
          url := 'https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-market-scanner',
          headers := jsonb_build_object(
            'Content-Type','application/json',
            'x-monitor-secret',(
              select decrypted_secret from vault.decrypted_secrets
              where name='MONITOR_SECRET'
              order by updated_at desc,created_at desc limit 1
            )
          ),
          body := jsonb_build_object('dry_run',false,'limit',20,'timeframes',jsonb_build_array('5M','1H','4H')),
          timeout_milliseconds := 120000
        ) as request_id
      )
      select private.track_crypto_operational_http_request('crypto-market-scanner',request_id) from request;
    $cmd$
  );

  if exists(select 1 from cron.job where jobname='crypto-lab-incident-reconciliation') then
    perform cron.unschedule('crypto-lab-incident-reconciliation');
  end if;
  perform cron.schedule('crypto-lab-incident-reconciliation','*/5 * * * *','select private.reconcile_crypto_operational_incidents();');
end $$;