create table if not exists public.crypto_signal_monitors (
  id uuid default gen_random_uuid() not null,
  symbol text not null,
  timeframe text not null,
  direction text not null,
  strength integer,
  entry_low numeric not null,
  entry_high numeric not null,
  stop numeric not null,
  tp1 numeric,
  tp2 numeric,
  tp3 numeric,
  status text default 'WAITING'::text not null,
  entry_notified boolean default false not null,
  tp1_notified boolean default false not null,
  tp2_notified boolean default false not null,
  tp3_notified boolean default false not null,
  stop_notified boolean default false not null,
  last_price numeric,
  last_checked_at timestamp with time zone,
  activated_at timestamp with time zone,
  closed_at timestamp with time zone,
  close_type text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint crypto_signal_monitors_direction_check CHECK (direction = ANY (ARRAY['LONG'::text, 'SHORT'::text])),
  constraint crypto_signal_monitors_pkey PRIMARY KEY (id),
  constraint crypto_signal_monitors_status_check CHECK (status = ANY (ARRAY['WAITING'::text, 'ACTIVE'::text, 'CLOSED'::text]))
);
