import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const ORIGIN="https://1specnazov1.github.io",HOST="1specnazov1.github.io",CONFIRM="https://txhzxbizjpinowepfjkm.supabase.co/functions/v1/crypto-lab-v79-confirm",LEGAL=["terms","privacy","risk"],MAX=16000;
function cors(o:string){return {"Access-Control-Allow-Origin":o,"Access-Control-Allow-Headers":"content-type, x-client-info","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Max-Age":"86400",Vary:"Origin"};}
function out(b:unknown,s:number,o:string){return Response.json(b,{status:s,headers:{...cors(o),"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
function clean(v:unknown,n:number){return String(v??"").replace(/[\r\n\u0000-\u001f\u007f]+/g," ").trim().slice(0,n)}
function email(v:string){return v.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function strong(v:string){return v.length>=10&&v.length<=72&&/[a-z]/.test(v)&&/[A-Z]/.test(v)&&/\d/.test(v)&&!/[\u0000-\u001f\u007f]/.test(v)}
async function hmac(v:string,k:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(k),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const s=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(v));return [...new Uint8Array(s)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function ip(r:Request){return clean(r.headers.get("cf-connecting-ip")||r.headers.get("x-real-ip")||r.headers.get("x-forwarded-for")?.split(",")[0]||"unknown",80)}
async function captcha(secret:string,token:string,remote:string,id?:string){const f=new FormData();f.append("secret",secret);f.append("response",token);if(remote!=="unknown")f.append("remoteip",remote);if(id)f.append("idempotency_key",id);try{const r=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:f});const b=await r.json().catch(()=>({}));return r.ok&&b?.success===true&&String(b?.hostname||"")===HOST&&String(b?.action||"")==="crypto_register"}catch{return false}}
Deno.serve(async req=>{const origin=req.headers.get("origin")||"";if(req.method==="OPTIONS"){if(origin!==ORIGIN)return new Response(null,{status:403});return new Response(null,{status:204,headers:cors(origin)})}if(origin!==ORIGIN)return Response.json({ok:false,error:"Origin not allowed"},{status:403});
 const url=Deno.env.get("SUPABASE_URL")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",siteKey=Deno.env.get("CRYPTO_TURNSTILE_SITE_KEY")||"",turnSecret=Deno.env.get("CRYPTO_TURNSTILE_SECRET_KEY")||"";if(!url||!service)return out({ok:false,error:"Server configuration unavailable"},503,origin);const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
 const [{data:runtime},{data:portal},{data:docs,error:docErr}]=await Promise.all([admin.from("crypto_commercial_runtime_flags").select("public_registration_enabled,production_launch_authorized").eq("singleton",true).maybeSingle(),admin.from("crypto_account_portal_config").select("registration_enabled,mode").eq("singleton",true).maybeSingle(),admin.from("crypto_legal_documents").select("document_key,version,effective_at,url_path").eq("active",true).in("document_key",LEGAL).order("document_key")]);
 const documents=(docs||[]).map((d:any)=>({key:d.document_key,version:d.version,effective_at:d.effective_at,url:d.url_path}));const legalReady=!docErr&&documents.length===LEGAL.length&&LEGAL.every(k=>documents.some(d=>d.key===k));const mail=!!Deno.env.get("RESEND_API_KEY")?.trim()&&!!Deno.env.get("CRYPTO_MAIL_FROM")?.trim();const enabled=runtime?.public_registration_enabled===true&&runtime?.production_launch_authorized===true&&portal?.registration_enabled===true&&!!siteKey&&!!turnSecret&&mail&&legalReady;
 if(req.method==="GET")return out({ok:true,enabled,registration_mode:enabled?"public_free":"disabled",free_access:true,captcha_provider:"turnstile",site_key:enabled?siteKey:null,captcha_action:"crypto_register",password_min_length:10,required_legal_keys:LEGAL,documents,readiness:{feature_flag:runtime?.public_registration_enabled===true,portal:portal?.registration_enabled===true,turnstile:!!siteKey&&!!turnSecret,mail_provider:mail,mail_provider_code:mail?"resend":"none",legal_documents:legalReady}},200,origin);if(req.method!=="POST")return out({ok:false,error:"Method not allowed"},405,origin);if(!enabled)return out({ok:false,error:"Registration is temporarily unavailable",code:"REGISTRATION_DISABLED"},503,origin);
 let requestId:string|undefined;const finish=async(o:string,reason?:string,userId?:string)=>{if(requestId)await admin.rpc("finish_crypto_registration_attempt",{p_request_id:requestId,p_outcome:o,p_reason:reason||null,p_user_id:userId||null})};
 try{const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>MAX)return out({ok:false,error:"Request too large"},413,origin);const b=JSON.parse(raw||"{}"),e=clean(b.email,254).toLowerCase(),p=String(b.password||""),name=clean(b.display_name,80),locale=["ru","uk","en"].includes(clean(b.locale,2))?clean(b.locale,2):"ru",tz=clean(b.timezone,80)||"Europe/Kyiv",token=clean(b.captcha_token,2048),honeypot=clean(b.website,200),submitted=Array.isArray(b.legal_acceptances)?b.legal_acceptances:[],map=new Map(submitted.map((x:any)=>[clean(x?.key,20),clean(x?.version,40)]));const legalCurrent=documents.every(d=>map.get(d.key)===d.version);const remote=ip(req),ipHash=await hmac(`ip:${remote}`,service),emailHash=await hmac(`email:${e}`,service),uaHash=await hmac(`ua:${clean(req.headers.get("user-agent"),500)}`,service);const {data:res,error:resErr}=await admin.rpc("reserve_crypto_registration_attempt",{p_ip_hash:ipHash,p_email_hash:emailHash});if(resErr)throw resErr;requestId=res?.request_id;if(!res?.allowed)return out({ok:false,error:"Too many registration attempts",code:"RATE_LIMITED",retry_after:3600},429,origin);if(honeypot){await finish("honeypot","honeypot");return out({ok:true,status:"confirmation_pending"},202,origin)}if(!email(e)||!strong(p)){await finish("invalid_input","validation");return out({ok:false,error:"Check email and password requirements",code:"INVALID_INPUT"},400,origin)}if(!legalCurrent){await finish("invalid_input","legal_consent");return out({ok:false,error:"Current legal documents must be accepted",code:"LEGAL_CONSENT_REQUIRED",documents},409,origin)}if(!token||!await captcha(turnSecret,token,remote,requestId)){await finish("captcha_failed","verification_failed");return out({ok:false,error:"CAPTCHA verification failed",code:"CAPTCHA_FAILED"},400,origin)}
 const {data:link,error:linkErr}=await admin.auth.admin.generateLink({type:"signup",email:e,password:p,options:{data:{display_name:name||null,language:locale,timezone:tz}}});if(linkErr){const m=String(linkErr.message||"").toLowerCase();if(m.includes("already")||m.includes("registered")||m.includes("exists")){await finish("duplicate","existing_email");return out({ok:true,status:"confirmation_pending"},202,origin)}throw linkErr}const hash=link?.properties?.hashed_token,userId=link?.user?.id;if(!hash||!userId)throw new Error("Confirmation token unavailable");for(const d of documents){const {error}=await admin.rpc("service_accept_crypto_legal",{p_user_id:userId,p_document_key:d.key,p_document_version:d.version,p_locale:locale,p_source:"registration",p_ip_hash:ipHash,p_user_agent_hash:uaHash});if(error){await admin.auth.admin.deleteUser(userId).catch(()=>{});throw error}}
 const action=`${CONFIRM}?token_hash=${encodeURIComponent(hash)}`;const mr=await fetch(`${url}/functions/v1/crypto-lab-mail-dispatch`,{method:"POST",headers:{Authorization:`Bearer ${service}`,apikey:service,"Content-Type":"application/json"},body:JSON.stringify({to:e,template:"signup_confirmation",locale,action_url:action,idempotency_key:`signup-${requestId}`})});const mb=await mr.json().catch(()=>({}));if(!mr.ok||!mb?.ok){await admin.auth.admin.deleteUser(userId).catch(()=>{});await finish("mail_failed","mail_unavailable");return out({ok:false,error:"Confirmation email could not be sent",code:"MAIL_UNAVAILABLE"},503,origin)}await finish("accepted",undefined,userId);return out({ok:true,status:"confirmation_pending",plan:"FREE"},202,origin)
 }catch(error){console.error("crypto-lab-v79-register",error);await finish("internal_error",clean(error instanceof Error?error.message:String(error),240));return out({ok:false,error:"Registration is temporarily unavailable",code:"INTERNAL_ERROR"},500,origin)}});